"""Config domains: generated adapters match config/defaults, ConfigFile loads them.

1. Every config/adapters/<Domain>Adapter.qml (generated by
   tools/config/gen_adapters.cjs) is instantiated offscreen and every key it
   declares, at any depth, is compared with config/defaults/<domain>.js: same
   key set, same value (after the QML type's conversion, so an `int` key with
   a fractional default would fail), and the declared type agrees with
   config/meta/AdapterTypes.js / the inference rules.
2. KeybindsAdapter carries every CoreBinds.js bind with its default combo and
   action, and the default custom binds.
3. ConfigFile.qml (one domain's FileView) is driven through a stub FileView:
   first load validates + marks ready, a missing file falls back to the
   defaults, a reload fills in missing top-level keys, adapter edits are
   written unless the store pauses auto-save.
4. The real Config.qml wires one ConfigFile per domain: once every file has
   loaded, initialLoadComplete flips and Config.<domain>.<key> reads the
   adapters (Quickshell types stubbed).
"""
import json
import subprocess
import tempfile
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.qmlharness import REPO, Harness  # noqa: E402
from PySide6.QtCore import QObject  # noqa: E402
from PySide6.QtTest import QTest  # noqa: E402

failures: list[str] = []


def check(ok, msg):
    print(("PASS " if ok else "FAIL ") + msg)
    if not ok:
        failures.append(msg)


node = r"""
const path = require('path');
const { loadLibrary } = require(path.resolve('tests/lib/qmljs.cjs'));
const gen = require(path.resolve('tools/config/gen_adapters.cjs'));
const out = { defaults: {}, types: loadLibrary('config/meta/AdapterTypes.js').types };
for (const f of require('fs').readdirSync('config/defaults')) {
  const d = f.replace(/\.js$/, '');
  out.defaults[d] = loadLibrary('config/defaults/' + f).data;
}
const core = loadLibrary('config/CoreBinds.js');
out.core = core.BINDS.map(b => ({ path: core.path(b), modifiers: b.modifiers, key: b.key, action: core.actionId(b) }));
out.custom = loadLibrary('config/CustomBindDefaults.js').binds();
out.appId = loadLibrary('modules/globals/BrandActions.js').appId;
process.stdout.write(JSON.stringify(out));
"""
ref = json.loads(subprocess.run(["node", "-e", node], cwd=REPO, capture_output=True, text=True, check=True).stdout)

h = Harness("config-adapters")
h.singleton("testlog", "ProcLog", "QtObject { property var last: null }")
h.module("Quickshell.Io", {
    "Process": """import testlog
QtObject {
    id: p
    property var command: []
    property bool running: false
    property int starts: 0
    signal exited(int exitCode, int exitStatus)
    onRunningChanged: if (running) { starts++; ProcLog.last = p; }
}""",
    "JsonAdapter": "QtObject {}",
    "JsonObject": "QtObject {}",
    # Quickshell's loadFailed passes this enum's value (a number), not a name;
    # same order as Quickshell/Io/quickshell-io.qmltypes.
    "FileViewError": "QtObject { enum Value { Success, Unknown, FileNotFound, PermissionDenied, NotAFile } }",
    "FileView": """QtObject {
    property string path
    property bool atomicWrites
    property bool watchChanges
    property QtObject adapter
    property string content: ""
    property bool exists: true
    property int writes: 0
    property int reloads: 0
    signal loaded
    signal loadFailed(var error)
    signal fileChanged
    signal adapterUpdated
    function text() { return content; }
    function setText(t) { content = t; exists = true; }
    function reload() { reloads++; }
    function writeAdapter() { writes++; }
}""",
})

QML_TYPE = {"int": "int", "double": "real", "bool": "bool", "QString": "string",
            "QStringList": "list<string>", "QVariantList": "list<var>", "QVariant": "var"}


def infer(v):
    if isinstance(v, bool):
        return "bool"
    if isinstance(v, (int, float)):
        return "real"
    if isinstance(v, str):
        return "string"
    if isinstance(v, list):
        return "list<string>" if v and all(isinstance(x, str) for x in v) else "list<var>"
    return "JsonObject" if isinstance(v, dict) else "var"


def dump(obj):
    """{key: (qmlType, value)} of a QObject's own declared properties, recursively."""
    mo = obj.metaObject()
    res = {}
    for i in range(QObject.staticMetaObject.propertyCount(), mo.propertyCount()):
        p = mo.property(i)
        n, t = p.name(), p.typeName()
        if t.endswith("*"):
            res[n] = ("JsonObject", dump(h.eval(obj, n)))
        else:
            res[n] = (QML_TYPE.get(t, t), json.loads(h.eval(obj, f"JSON.stringify({n}) ?? 'null'")))
    return res


def same(a, b):
    if isinstance(a, (int, float)) and isinstance(b, (int, float)) and not isinstance(a, bool):
        return float(a) == float(b)
    return a == b


adapters = REPO / "config/adapters"


def compare(tree, dflt, prefix, types, bad):
    """Append to `bad` every key/type/value of `tree` that differs from the defaults."""
    if set(tree) != set(dflt):
        bad.append(f"{prefix or '<root>'} keys differ: {sorted(set(tree) ^ set(dflt))}")
    for k in tree.keys() & dflt.keys():
        t, v = tree[k]
        p = prefix + k
        want = types.get(p) or infer(dflt[k])
        if t != want:
            bad.append(f"{p}: type {t}, want {want}")
        if t == "JsonObject":
            compare(v, dflt[k], p + ".", types, bad)
        elif not same(v, dflt[k]):
            bad.append(f"{p}: {json.dumps(v)[:60]} != default {json.dumps(dflt[k])[:60]}")


def load_adapter(name):
    # Same layout as the repo so the adapters' relative JS imports resolve.
    h.copy(f"config/adapters/{name}.qml", dest="config/adapters")
    return h.load(h.write(f"import QtQuick\n{name} {{}}", dest="config/adapters"), auto_stub=False)


for domain, defaults in sorted(ref["defaults"].items()):
    name = domain[0].upper() + domain[1:] + "Adapter"
    obj = load_adapter(name)
    types = ref["types"].get(domain, {})
    bad: list[str] = []
    compare(dump(obj), defaults, "", types, bad)
    check(not bad, f"{name}: every key/type/default matches config/defaults/{domain}.js" + (": " + "; ".join(bad[:5]) if bad else ""))

kb = load_adapter("KeybindsAdapter")
bad = []
for b in ref["core"]:
    expr = ref["appId"] + "." + b["path"]
    got = json.loads(h.eval(kb, f"JSON.stringify({{m: {expr}.modifiers, k: {expr}.key, a: {expr}.action}})"))
    if got != {"m": b["modifiers"], "k": b["key"], "a": {"id": b["action"], "args": {}}}:
        bad.append(f"{b['path']}: {got}")
check(not bad, f"KeybindsAdapter: all {len(ref['core'])} core binds with default combo/action" + (": " + "; ".join(bad[:3]) if bad else ""))
check(json.loads(h.eval(kb, "JSON.stringify(custom)")) == ref["custom"] and len(ref["custom"]) > 50,
      f"KeybindsAdapter: {len(ref['custom'])} default custom binds")
check(json.loads(h.eval(kb, "JSON.stringify(disabled)")) == [], "KeybindsAdapter: no core bind disabled by default")

# ---- ConfigFile: load / validate / fill / write-back ----
h.copy("config/ConfigFile.qml")
scene = h.load("""import QtQuick
QtObject {
    id: store
    property string configDir: "/cfg"
    property string presetDir: "/preset"
    property bool pauseAutoSave: false
    property int legacyCalls: 0
    property ConfigFile file: ConfigFile {
        store: store
        name: "demo"
        defaults: ({ "a": 1, "b": { "c": "x" }, "list": [1, 2] })
        onBeforeValidate: store.legacyCalls++
        adapter: QtObject {}
    }
}""", auto_stub=False)
f = h.eval(scene, "file")
check(h.eval(f, "path") == "/cfg/demo.json", "path is <configDir>/<name>.json")
h.eval(f, "content = JSON.stringify({ a: 5 }); loaded()")
stored = json.loads(h.eval(f, "content"))
check(h.eval(f, "ready") is True, "first load marks the domain ready")
check(stored == {"a": 5, "b": {"c": "x"}, "list": [1, 2]}, f"first load validates/merges with defaults: {stored}")
check(h.eval(scene, "legacyCalls") == 1, "beforeValidate runs on load")
h.eval(f, "content = JSON.stringify({ a: 7 }); loaded()")
check(json.loads(h.eval(f, "content")) == {"a": 7, "b": {"c": "x"}, "list": [1, 2]}, "reload fills missing top-level keys")
h.eval(f, "writes = 0; adapterUpdated()")
check(h.eval(f, "writes") == 1, "adapter edits are written back")
h.eval(scene, "pauseAutoSave = true")
h.eval(f, "adapterUpdated()")
check(h.eval(f, "writes") == 1, "no write while the store pauses auto-save")
h.eval(scene, "pauseAutoSave = false")
h.eval(f, "fileChanged()")
check(h.eval(f, "reloads") >= 1 and h.eval(scene, "pauseAutoSave") is False, "external change reloads with auto-save paused")

BROKEN = """import QtQuick
QtObject {
    id: store
    property string configDir: "/cfg"
    property string presetDir: "/preset"
    property bool pauseAutoSave: false
    property var reports: []
    function configMalformed(name, backup, replaced) { reports = reports.concat([[name, backup, replaced]]); }
    property ConfigFile file: ConfigFile {
        store: store
        name: "bad"
        defaults: ({ "a": 1 })
        adapter: QtObject {}
    }
}"""
broken = h.load(BROKEN, auto_stub=False)
bf = h.eval(broken, "file")
h.eval(bf, "content = '{not json'; loaded()")
cmd = json.loads(h.eval(bf, "JSON.stringify(quarantine.command)") or "[]")
check(h.eval(bf, "quarantine.starts") == 1 and list(cmd[:3]) == ["cp", "--", "/cfg/bad.json"]
      and str(cmd[3]).startswith("/cfg/bad.json.bad-"), f"malformed JSON is first backed up as <file>.bad-<timestamp>: {cmd}")
check(h.eval(bf, "content") == "{not json", "…and not replaced before the backup exists")
h.eval(bf, "quarantine.exited(0, 0)")
check(json.loads(h.eval(bf, "content")) == {"a": 1} and h.eval(bf, "ready") is True, "after the backup the defaults replace it")
rep = h.eval(broken, "JSON.stringify(reports)")
check(json.loads(rep) == [["bad", cmd[3], True]], f"the user is told where the backup is: {rep}")

failed = h.load(BROKEN, auto_stub=False)
ff = h.eval(failed, "file")
h.eval(ff, "content = '{not json'; loaded()")
h.eval(ff, "quarantine.exited(1, 0)")
check(h.eval(ff, "content") == "{not json" and h.eval(ff, "ready") is True, "a failed backup never overwrites the file")
h.eval(ff, "writes = 0; adapterUpdated()")
check(h.eval(ff, "writes") == 0, "…nor do adapter edits while it is broken")
check(json.loads(h.eval(failed, "JSON.stringify(reports)"))[0][2] is False, "…and the user is told it was kept")

later = h.load(BROKEN, auto_stub=False)
lf = h.eval(later, "file")
h.eval(lf, "content = JSON.stringify({ a: 2 }); loaded()")
h.eval(lf, "content = '{oops'; loaded()")
check(h.eval(lf, "quarantine.starts") == 1, "a file broken after startup is backed up too")
h.eval(lf, "quarantine.exited(0, 0)")
check(h.eval(lf, "content") == "{oops", "…but left for the user to fix (no silent reset)")
h.eval(lf, "writes = 0; adapterUpdated()")
check(h.eval(lf, "writes") == 0, "…and adapter edits do not overwrite it")
h.eval(lf, "content = JSON.stringify({ a: 3 }); loaded()")
h.eval(lf, "writes = 0; adapterUpdated()")
check(h.eval(lf, "writes") == 1, "once fixed, edits are written again")

# Missing file: the preset copy runs cp with argv (no generated QML).
def missing_scene(name):
    return h.load("""import QtQuick
import testlog
QtObject {
    id: store
    property string configDir: "/cfg"
    property string presetDir: "/preset"
    property bool pauseAutoSave: false
    property var log: ProcLog
    property ConfigFile file: ConfigFile {
        store: store
        name: "%s"
        defaults: ({ "a": 1 })
        adapter: QtObject {}
    }
}""" % name, auto_stub=False)


ms = missing_scene("miss")
mf = h.eval(ms, "file")
h.eval(mf, "loadFailed('FileNotFound')")
cp = h.eval(ms, "log.last ? log.last.command : null")
cp = list(cp.toVariant()) if hasattr(cp, "toVariant") else cp
check(cp == ["cp", "-n", "--", "/preset/miss.json", "/cfg/miss.json"], f"missing file: preset copied with cp argv: {cp}")
before = h.eval(mf, "reloads")
h.eval(ms, "log.last.exited(0, 0)")
check(h.eval(mf, "reloads") == before + 1, "missing file: reloads after the preset copy")
ms2 = missing_scene("nopreset")
mf2 = h.eval(ms2, "file")
h.eval(mf2, "loadFailed('FileNotFound')")
h.eval(ms2, "log.last.exited(1, 0)")
check(json.loads(h.eval(mf2, "content") or "null") == {"a": 1} and h.eval(mf2, "ready") is True,
      "missing file without a preset: defaults written, domain ready")
ms3 = missing_scene("enumerr")
mf3 = h.eval(ms3, "file")
h.eval(mf3, "loadFailed(2)")  # FileViewError.FileNotFound (quickshell-io.qmltypes order)
h.eval(ms3, "log.last.exited(1, 0)")
check(h.eval(mf3, "ready") is True, "missing file reported as the FileViewError value: domain ready")

# ---- Config.qml wiring (own harness: the repo layout under qs/) ----
w = Harness("config-wiring")
w.module("Quickshell", {
    "Singleton": "QtObject { default property list<QtObject> data }",
    "Scope": "QtObject { default property list<QtObject> data }",
    "Quickshell": "pragma Singleton\nQtObject { function dataPath(f) { return '/data/' + f; } function env(n) { return ''; } }",
})
w.module("Quickshell.Io", {
    "Process": "QtObject { property var command; property bool running; signal exited(int exitCode, int exitStatus) }",
    "JsonAdapter": "QtObject {}",
    "JsonObject": "QtObject {}",
    "FileView": (h.root / "Quickshell/Io/FileView.qml").read_text(),
})
w.module("qs.modules.globals", {"GlobalStates": "pragma Singleton\nQtObject { property var wallpaperManager: null; function markShellChanged() {} }"})
w.module("qs.modules.theme", {"Colors": "pragma Singleton\nQtObject { property color primary: 'red' }"})
w.module("qs.modules.services", {
    "GameModeClient": "pragma Singleton\nQtObject { property bool toggled: false }",
    "Notifications": "pragma Singleton\nQtObject { property var last: null; function notifyInternal(o) { last = o; return 1; } }",
})
w.module("qs.config.adapters", {p.stem: p.read_text() for p in sorted(adapters.glob("*.qml"))})
w.copy("config/CustomBindDefaults.js", dest="qs/config")
cfg = w.load(w.copy("config/Config.qml", dest="qs/config", strip_singleton=True), auto_stub=False)
check(w.eval(cfg, "initialLoadComplete") is False, "not complete before the files load")
w.eval(cfg, 'configMalformed("bar", "/cfg/bar.json.bad-1", true)')
QTest.qWait(10)
note = w.eval(cfg, "JSON.stringify(Services.Notifications.last)")
check(note and "bar.json.bad-1" in note and "critical" in note, f"a malformed config file is reported to the user: {note}")
for d in ref["defaults"]:
    w.eval(cfg, f"{d}Loader.content = '{{}}'; {d}Loader.loaded()")
check(w.eval(cfg, "initialLoadComplete") is True, f"initialLoadComplete after all {len(ref['defaults'])} domains loaded")
check(all(w.eval(cfg, f"{d}Ready") for d in ref["defaults"]), "every <domain>Ready follows its ConfigFile")
check(json.loads(w.eval(cfg, "generalLoader.content")).get("onboardingDone") is True,
      "general.json without onboardingDone counts as an existing install")
check(w.eval(cfg, "bar.position") == ref["defaults"]["bar"]["position"]
      and w.eval(cfg, "theme.glass.amount") == ref["defaults"]["theme"]["glass"]["amount"]
      and w.eval(cfg, "loader === themeLoader"), "Config.<domain>.<key> reads the adapters; Config.loader is the theme file")
w.eval(cfg, "keybindsLoader.content = ''; keybindsLoader.loaded()")
check(w.eval(cfg, "keybindsInitialLoadComplete") is True and w.eval(cfg, "keybindsLoader.writes") >= 1,
      "binds.json is created on first load")
check(w.eval(cfg, f"keybindsLoader.adapter.{ref['appId']}.system.keybinds.key") == "SLASH",
      "Config.keybindsLoader.adapter exposes the core binds")

# Startup seeding/migration pass the dirs as argv and still work.
seed = [str(a) for a in w.eval(cfg, "ensureConfigDir.command").toVariant()]
mig = [str(a) for a in w.eval(cfg, "migrateCompositorConfig.command").toVariant()]
check(seed[:2] == ["sh", "-c"] and mig[:2] == ["sh", "-c"] and "configDir" not in seed[2] and "/" not in seed[2].replace("$src/", "").replace("$dst/", "").replace("2>/dev/null", "")
      and "/" not in mig[2].replace("$d/", ""), f"config seeding/migration scripts take dirs as args: {seed[:3]} {mig[:3]}")
with tempfile.TemporaryDirectory() as tmp:
    pre, dst = Path(tmp, "pre's $(x)"), Path(tmp, "cfg dir/'q")
    pre.mkdir()
    (pre / "bar.json").write_text('{"preset": 1}')
    seed[4], seed[5] = str(pre), str(dst)
    subprocess.run(seed, check=True, capture_output=True)
    check(json.loads((dst / "bar.json").read_text()) == {"preset": 1}, "seeding copies preset files into the config dir")
    (dst / "hyprland.json").write_text("{}")
    (dst / "compositor.json").unlink(missing_ok=True)
    mig[4] = str(dst)
    subprocess.run(mig, check=True, capture_output=True)
    check((dst / "compositor.json").is_file() and not (dst / "hyprland.json").exists(), "hyprland.json migrates to compositor.json")

print("config-adapters:", "FAIL" if failures else "ok", f"({len(failures)} failure(s))")
h.exit(1 if failures else 0)
