#!/usr/bin/env node
// Generate the typed JsonAdapter of every config domain into config/adapters/
// from the single source of truth, config/defaults/<domain>.js (keys, default
// values) plus config/meta/AdapterTypes.js (QML types a value does not tell),
// and the binds.json adapter from config/CoreBinds.js. Config.qml instantiates
// them (one ConfigFile per domain); nothing else declares config keys.
//   node tools/config/gen_adapters.cjs           write the files (`make schema`)
//   node tools/config/gen_adapters.cjs --check   exit 1 if they are stale
// The output is already qmlformat-clean (.qmlformat.ini).
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const repo = path.resolve(__dirname, '../..');
const { loadLibrary } = require(path.join(repo, 'tests/lib/qmljs.cjs'));
const outDir = path.join(repo, 'config/adapters');
const IND = '    ';

const plain = v => JSON.parse(JSON.stringify(v));
const isObject = v => v !== null && typeof v === 'object' && !Array.isArray(v);
const cap = s => s.charAt(0).toUpperCase() + s.slice(1);

// A JSON value laid out the way qmlformat prints it; `ind` is the
// indentation of the line the value starts on.
function value(v, ind) {
    if (Array.isArray(v)) {
        if (!v.length) return '[]';
        if (!v.some(x => isObject(x) || (Array.isArray(x) && x.some(isObject))))
            return '[' + v.map(x => value(x, ind)).join(', ') + ']';
        return '[\n' + v.map(x => ind + IND + value(x, ind + IND)).join(',\n') + '\n' + ind + ']';
    }
    if (isObject(v)) {
        const keys = Object.keys(v);
        if (!keys.length) return '{}';
        return '{\n' + keys.map(k => ind + IND + JSON.stringify(k) + ': ' + value(v[k], ind + IND)).join(',\n') + '\n' + ind + '}';
    }
    return JSON.stringify(v);
}

// `property var x: ({...})`: qmlformat indents the object one level deeper.
function varValue(v, ind) {
    return isObject(v) ? '(' + value(v, ind + IND) + ')' : value(v, ind);
}

function inferType(v) {
    if (typeof v === 'boolean') return 'bool';
    if (typeof v === 'number') return 'real';
    if (typeof v === 'string') return 'string';
    if (Array.isArray(v)) return v.length && v.every(x => typeof x === 'string') ? 'list<string>' : 'list<var>';
    if (isObject(v)) return 'JsonObject';
    return 'var';
}

const TYPES = new Set(['bool', 'int', 'real', 'string', 'var', 'list<string>', 'list<var>']);

function properties(obj, types, prefix, ind, errors, domain) {
    const out = [];
    for (const [key, v] of Object.entries(obj)) {
        const p = prefix + key;
        const type = types[p] || inferType(v);
        if (types[p] && !TYPES.has(types[p])) errors.push(`${domain}.${p}: unknown type "${types[p]}" in AdapterTypes.js`);
        if (type === 'JsonObject') {
            out.push(`${ind}property JsonObject ${key}: JsonObject {`);
            out.push(...properties(v, types, p + '.', ind + IND, errors, domain));
            out.push(`${ind}}`);
        } else {
            if (type === 'int' && !Number.isInteger(v)) errors.push(`${domain}.${p}: int default ${v} is not whole`);
            out.push(`${ind}property ${type} ${key}: ${type === 'var' ? varValue(v, ind) : value(v, ind)}`);
        }
    }
    return out;
}

function header(source) {
    return [
        `// Generated by tools/config/gen_adapters.cjs from ${source}.`,
        '// Do not edit: change the source and run `make schema`.',
    ];
}

function domainAdapter(domain, data, types, errors) {
    const seen = new Set();
    const walk = (o, pre) => Object.entries(o).forEach(([k, v]) => {
        seen.add(pre + k);
        if (isObject(v) && !types[pre + k]) walk(v, pre + k + '.');
    });
    walk(data, '');
    for (const p of Object.keys(types))
        if (!seen.has(p)) errors.push(`AdapterTypes.js: ${domain}.${p} is not a key of config/defaults/${domain}.js`);
    return [
        ...header(`config/defaults/${domain}.js and config/meta/AdapterTypes.js`),
        'import Quickshell.Io',
        '',
        'JsonAdapter {',
        ...properties(data, types, '', IND, errors, domain),
        '}',
        '',
    ].join('\n');
}

// binds.json: the shell's own binds (CoreBinds.js) under the app id root,
// the list of disabled core binds and the default custom binds.
function keybindsAdapter(core, appId) {
    const bind = (b, ind) => {
        const id = b.action.indexOf('.') !== -1 ? JSON.stringify(b.action) : `BrandActions.action(${JSON.stringify(b.action)})`;
        return [
            `${ind}property JsonObject ${b.name}: JsonObject {`,
            `${ind}${IND}property list<string> modifiers: ${value(b.modifiers, ind + IND)}`,
            `${ind}${IND}property string key: ${JSON.stringify(b.key)}`,
            `${ind}${IND}property var action: ({`,
            `${ind}${IND}${IND}${IND}"id": ${id},`,
            `${ind}${IND}${IND}${IND}"args": {}`,
            `${ind}${IND}${IND}})`,
            `${ind}}`,
        ];
    };
    const sections = [];
    for (const b of core.BINDS) if (b.section && !sections.includes(b.section)) sections.push(b.section);
    const lines = [`${IND}property JsonObject ${appId}: JsonObject {`];
    for (const b of core.BINDS.filter(x => !x.section)) lines.push(...bind(b, IND + IND));
    for (const s of sections) {
        lines.push(`${IND}${IND}property JsonObject ${s}: JsonObject {`);
        for (const b of core.BINDS.filter(x => x.section === s)) lines.push(...bind(b, IND + IND + IND));
        lines.push(`${IND}${IND}}`);
    }
    lines.push(`${IND}}`);
    return [
        ...header('config/CoreBinds.js and config/CustomBindDefaults.js'),
        'import Quickshell.Io',
        'import "../CustomBindDefaults.js" as CustomBindDefaults',
        'import "../../modules/globals/BrandActions.js" as BrandActions',
        '',
        'JsonAdapter {',
        ...lines,
        `${IND}// Core binds switched off in the editor ("launcher", "system.tools").`,
        `${IND}property list<string> disabled: []`,
        `${IND}property list<var> custom: CustomBindDefaults.binds()`,
        `${IND}// One-shot binds.json migrations already applied (KeybindsFile).`,
        `${IND}property list<string> migrations: []`,
        '}',
        '',
    ].join('\n');
}

function build() {
    const errors = [];
    const files = {};
    const cache = new Map();
    const lib = rel => loadLibrary(path.join(repo, rel), cache);
    const types = plain(lib('config/meta/AdapterTypes.js').types);
    const domains = fs.readdirSync(path.join(repo, 'config/defaults')).filter(f => f.endsWith('.js')).map(f => f.slice(0, -3)).sort();
    for (const d of Object.keys(types))
        if (!domains.includes(d)) errors.push(`AdapterTypes.js: unknown domain "${d}"`);
    for (const d of domains)
        files[`${cap(d)}Adapter.qml`] = domainAdapter(d, plain(lib(`config/defaults/${d}.js`).data), types[d] || {}, errors);
    const brand = lib('modules/globals/BrandActions.js');
    files['KeybindsAdapter.qml'] = keybindsAdapter(lib('config/CoreBinds.js'), brand.appId);
    return { files, errors };
}

if (require.main === module) {
    const mode = process.argv[2] || '';
    const { files, errors } = build();
    if (errors.length) {
        for (const e of errors) console.error(`error: ${e}`);
        process.exit(2);
    }
    const existing = fs.existsSync(outDir) ? fs.readdirSync(outDir).filter(f => f.endsWith('.qml')) : [];
    if (mode === '--check') {
        const stale = Object.keys(files).filter(n => {
            const p = path.join(outDir, n);
            return !fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== files[n];
        });
        const extra = existing.filter(n => !(n in files));
        for (const n of stale) console.log(`stale: config/adapters/${n}`);
        for (const n of extra) console.log(`extra: config/adapters/${n}`);
        process.exit(stale.length || extra.length ? 1 : 0);
    }
    fs.mkdirSync(outDir, { recursive: true });
    for (const n of existing) if (!(n in files)) fs.unlinkSync(path.join(outDir, n));
    for (const [n, text] of Object.entries(files)) fs.writeFileSync(path.join(outDir, n), text);
    console.log(`wrote ${Object.keys(files).length} files to config/adapters/`);
}

module.exports = { build, inferType };
