package niri

import (
	"fmt"
	"strings"

	"yozakura/backend/pkg/brand"
	"yozakura/backend/pkg/yozd/ipc"
)

// spawnArgs renders a startup command as niri's argv: spawn-at-startup does
// not go through a shell, so "a b" would be one program name. A plain
// command is split into one argument per word. A command with quoting or
// shell syntax, or a leading VAR=value assignment, runs as sh -c "<cmd>"
// (the same semantics as Hyprland's exec-once, which uses a shell).
func spawnArgs(cmd string) string {
	words := strings.Fields(cmd)
	if strings.ContainsAny(cmd, "'\"\\$`;|&<>*?()") || (len(words) > 0 && isEnvAssign(words[0])) {
		return kdlQuote("sh") + " " + kdlQuote("-c") + " " + kdlQuote(cmd)
	}
	for i, w := range words {
		words[i] = kdlQuote(w)
	}
	return strings.Join(words, " ")
}

// isEnvAssign reports whether w looks like NAME=value.
func isEnvAssign(w string) bool {
	name, _, ok := strings.Cut(w, "=")
	if !ok || name == "" {
		return false
	}
	for i, r := range name {
		if r == '_' || (r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (i > 0 && r >= '0' && r <= '9') {
			continue
		}
		return false
	}
	return true
}

func (g *Generator) GenerateStartup(exec []string, execOnce []string) string {
	var b strings.Builder
	if len(exec) == 0 && len(execOnce) == 0 {
		return ""
	}
	b.WriteString("// Generated by " + brand.Daemon + " (startup)\n")
	b.WriteString("// niri has no exec-recurrent; exec-once maps to spawn-at-startup.\n\n")
	for _, cmd := range execOnce {
		if strings.TrimSpace(cmd) == "" {
			continue
		}
		cmd = ipc.ResolveExecCommand(cmd)
		b.WriteString("spawn-at-startup " + spawnArgs(cmd) + "\n")
	}
	for _, cmd := range exec {
		if strings.TrimSpace(cmd) == "" {
			continue
		}
		cmd = ipc.ResolveExecCommand(cmd)
		b.WriteString(fmt.Sprintf("// niri does not re-run exec on reload; ignoring: %s\n", cmd))
	}
	return b.String()
}
