import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.globals
import "ColorUtils.js" as ColorUtils

// Firefox: palette-driven userChrome/userContent without any extension.
// For every default Firefox profile it writes chrome/<app>.css and
// chrome/<app>-content.css, makes userChrome.css / userContent.css @import
// them (existing user rules are kept; an import of the legacy app's file is
// switched over) and enables
// toolkit.legacyUserProfileCustomizations.stylesheets via user.js.
// Firefox reads these at startup, so palette changes apply on next launch.
QtObject {
    id: root

    function generate(Colors) {
        if (!Colors)
            return;
        try {
            const p = ColorUtils.palette(Colors);
            const rgba = (hex, a) => `rgba(${ColorUtils.rgbTriplet(hex)}, ${a})`;
            const scheme = ColorUtils.isDark(p.background) ? "dark" : "light";

            const chrome = `/* Generated by ${Brand.displayName} from the current Material palette. Do not edit. */
:root {
    color-scheme: ${scheme} !important;
    --${Brand.appId}-primary: ${p.primary};
    --${Brand.appId}-on-primary: ${p.overPrimary};

    /* Frame / tab strip */
    --lwt-accent-color: ${p.background} !important;
    --lwt-accent-color-inactive: ${p.background} !important;
    --lwt-text-color: ${p.overSurface} !important;
    --toolbox-bgcolor: ${p.background} !important;
    --toolbox-bgcolor-inactive: ${p.background} !important;
    --toolbox-textcolor: ${p.overSurface} !important;
    --toolbox-textcolor-inactive: ${p.overSurfaceVariant} !important;
    --tab-selected-bgcolor: ${p.surfaceContainerHigh} !important;
    --tab-selected-textcolor: ${p.overSurface} !important;
    --tab-hover-background-color: ${rgba(p.overSurface, 0.08)} !important;
    --tab-loading-fill: ${p.primary} !important;
    --tab-attention-icon-color: ${p.primary} !important;
    --lwt-tab-line-color: ${p.primary} !important;

    /* Toolbars */
    --toolbar-bgcolor: ${p.surfaceContainerHigh} !important;
    --toolbar-color: ${p.overSurface} !important;
    --toolbarbutton-icon-fill: ${p.overSurfaceVariant} !important;
    --toolbarbutton-icon-fill-attention: ${p.primary} !important;
    --toolbarbutton-hover-background: ${rgba(p.overSurface, 0.08)} !important;
    --toolbarbutton-active-background: ${rgba(p.overSurface, 0.14)} !important;
    --toolbarseparator-color: ${p.outlineVariant} !important;
    --chrome-content-separator-color: ${p.surfaceContainerHigh} !important;

    /* URL bar */
    --toolbar-field-background-color: ${p.surfaceContainer} !important;
    --toolbar-field-color: ${p.overSurface} !important;
    --toolbar-field-border-color: transparent !important;
    --toolbar-field-focus-background-color: ${p.surfaceContainerHighest} !important;
    --toolbar-field-focus-color: ${p.overSurface} !important;
    --toolbar-field-focus-border-color: ${p.primary} !important;
    --urlbar-box-bgcolor: ${p.surfaceContainerHighest} !important;
    --urlbar-box-text-color: ${p.overSurface} !important;
    --urlbar-box-hover-bgcolor: ${rgba(p.overSurface, 0.12)} !important;
    --urlbarView-highlight-background: ${p.primaryContainer} !important;
    --urlbarView-highlight-color: ${p.overPrimaryContainer} !important;
    --urlbarView-separator-color: ${p.outlineVariant} !important;
    --urlbarView-action-color: ${p.primary} !important;

    /* Popups, menus, panels */
    --arrowpanel-background: ${p.surfaceContainer} !important;
    --arrowpanel-color: ${p.overSurface} !important;
    --arrowpanel-border-color: ${p.outlineVariant} !important;
    --panel-separator-color: ${p.outlineVariant} !important;
    --menu-background-color: ${p.surfaceContainer} !important;
    --menu-color: ${p.overSurface} !important;
    --menuitem-hover-background-color: ${rgba(p.overSurface, 0.08)} !important;
    --menu-border-color: ${p.outlineVariant} !important;

    /* Sidebar */
    --sidebar-background-color: ${p.background} !important;
    --sidebar-text-color: ${p.overSurface} !important;
    --sidebar-border-color: ${p.outlineVariant} !important;
    --lwt-sidebar-background-color: ${p.background} !important;
    --lwt-sidebar-text-color: ${p.overSurface} !important;

    /* Accent (buttons, checkboxes, focus rings) */
    --color-accent-primary: ${p.primary} !important;
    --color-accent-primary-hover: ${ColorUtils.mix(p.primary, p.overPrimary, 0.1)} !important;
    --color-accent-primary-active: ${ColorUtils.mix(p.primary, p.overPrimary, 0.2)} !important;
    --button-text-color-primary: ${p.overPrimary} !important;
    --focus-outline-color: ${p.primary} !important;
    --tabpanel-background-color: ${p.background} !important;
}

#navigator-toolbox {
    background-color: var(--toolbox-bgcolor) !important;
    border-bottom-color: transparent !important;
}

#urlbar[focused] #urlbar-background {
    outline-color: ${p.primary} !important;
}

.tab-background[selected] {
    background: var(--tab-selected-bgcolor) !important;
}

#TabsToolbar .tabbrowser-tab[selected] .tab-label {
    color: var(--tab-selected-textcolor) !important;
}

::selection {
    background-color: ${p.primaryContainer} !important;
    color: ${p.overPrimaryContainer} !important;
}
`;

            const content = `/* Generated by ${Brand.displayName} from the current Material palette. Do not edit. */
@-moz-document url("about:newtab"), url("about:home"), url("about:privatebrowsing") {
    :root, body {
        --newtab-background-color: ${p.background} !important;
        --newtab-background-color-secondary: ${p.surfaceContainer} !important;
        --newtab-text-primary-color: ${p.overSurface} !important;
        --newtab-text-secondary-color: ${p.overSurfaceVariant} !important;
        --newtab-primary-action-background: ${p.primary} !important;
        --newtab-element-hover-color: ${p.surfaceContainerHigh} !important;
        --newtab-element-secondary-color: ${p.surfaceContainerHigh} !important;
        --newtab-wordmark-color: ${p.overSurface} !important;
        --color-accent-primary: ${p.primary} !important;
        background-color: ${p.background} !important;
        color: ${p.overSurface} !important;
    }
}
`;

            writerProcess.command = ["sh", "-c", root.script, Brand.appId + "-firefox", chrome, content, Brand.appId, Brand.legacyAppId];
            writerProcess.running = true;
        } catch (e) {
            console.error("FirefoxGenerator: generate failed:", e);
        }
    }

    // $1 <app>.css, $2 <app>-content.css, $3 app id, $4 legacy app id
    readonly property string script: `
        chrome_css="$1"; content_css="$2"; app="$3"; legacy="$4"
        pref='user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);'

        ensure_import() { # file, imported name, legacy imported name
            if [ -f "$1" ] && [ "$3" != "$2" ] && grep -qF "url(\\"$3\\")" "$1"; then
                sed "s|url(\\"$3\\")|url(\\"$2\\")|" "$1" > "$1.$app-tmp" && mv -f "$1.$app-tmp" "$1"
            fi
            if [ ! -f "$1" ]; then
                printf '@import url("%s");\\n' "$2" > "$1"
            elif ! grep -qF "url(\\"$2\\")" "$1"; then
                { printf '@import url("%s");\\n' "$2"; cat "$1"; } > "$1.$app-tmp" && mv -f "$1.$app-tmp" "$1"
            fi
        }

        write_if_changed() { # file, content
            if [ ! -f "$1" ] || [ "$(cat "$1")" != "$(printf '%s' "$2")" ]; then
                printf '%s' "$2" > "$1.$app-tmp" && mv -f "$1.$app-tmp" "$1"
            fi
        }

        for base in "$HOME/.mozilla/firefox" "\${XDG_CONFIG_HOME:-$HOME/.config}/mozilla/firefox"; do
            [ -f "$base/profiles.ini" ] || continue
            profiles="$( { [ -f "$base/installs.ini" ] && sed -n 's/^Default=//p' "$base/installs.ini"; \\
                awk -F= '/^\\[/{p=""; d=0} /^Path=/{p=$2} /^Default=1/{d=1} p!="" && d==1 {print p; p=""}' "$base/profiles.ini"; } | sort -u )"
            printf '%s\\n' "$profiles" | while IFS= read -r rel; do
                [ -n "$rel" ] || continue
                case "$rel" in /*) dir="$rel" ;; *) dir="$base/$rel" ;; esac
                [ -d "$dir" ] || continue
                mkdir -p "$dir/chrome" || continue
                write_if_changed "$dir/chrome/$app.css" "$chrome_css"
                write_if_changed "$dir/chrome/$app-content.css" "$content_css"
                ensure_import "$dir/chrome/userChrome.css" "$app.css" "$legacy.css"
                ensure_import "$dir/chrome/userContent.css" "$app-content.css" "$legacy-content.css"
                if ! grep -qs 'toolkit.legacyUserProfileCustomizations.stylesheets' "$dir/user.js"; then
                    printf '%s\\n' "$pref" >> "$dir/user.js"
                fi
            done
        done
    `

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("FirefoxGenerator: Theme generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: err => {
                const text = err ? err.toString().trim() : "";
                if (text)
                    console.error("FirefoxGenerator Error:", text);
            }
        }
    }
}
