import QtQuick
import Quickshell
import Quickshell.Io
import "ColorUtils.js" as ColorUtils
import qs.modules.globals

// Neovim: writes <cache dir>/nvim-palette.lua (a Lua table with a
// base16 palette + the raw Material roles). A user-side colorscheme
// (e.g. LazyVim + mini.base16, see e.g. ~/.config/nvim/colors/<name>.lua) loads it
// and watches the file, so running nvim instances recolor live.
QtObject {
    id: root

    function generate(Colors) {
        if (!Colors)
            return;
        try {
            const p = ColorUtils.palette(Colors);
            const dark = ColorUtils.isDark(p.background);
            const base16 = {
                base00: p.background,                 // default background
                base01: p.surfaceContainer,           // statusline, line number bg
                base02: p.surfaceContainerHighest,    // selection
                base03: p.outline,                    // comments, invisibles
                base04: p.overSurfaceVariant,         // dark foreground
                base05: p.overSurface,                // default foreground
                base06: p.inverseSurface,             // light foreground
                base07: p.overPrimaryContainer,       // lightest foreground
                base08: p.red,                        // variables, tags, deleted
                base09: p.tertiary,                   // numbers, constants
                base0A: p.yellow,                     // types, search
                base0B: p.green,                      // strings, inserted
                base0C: p.cyan,                       // escapes, regex
                base0D: p.primary,                    // functions
                base0E: p.magenta,                    // keywords
                base0F: p.error                       // deprecated, embedded
            };
            let lua = "-- Generated by " + Brand.displayName + " from the current Material palette. Do not edit.\n";
            lua += "return {\n";
            lua += "  dark = " + (dark ? "true" : "false") + ",\n";
            lua += "  base16 = {\n";
            for (const k in base16)
                lua += "    " + k + " = \"" + base16[k] + "\",\n";
            lua += "  },\n  roles = {\n";
            const keys = Object.keys(p).sort();
            for (let i = 0; i < keys.length; i++)
                lua += "    " + keys[i] + " = \"" + p[keys[i]] + "\",\n";
            lua += "  },\n}\n";

            const out = Brand.cacheDir + "/nvim-palette.lua";
            writerProcess.command = ["sh", "-c", root.script, Brand.appId + "-nvim", out, lua];
            writerProcess.running = true;
        } catch (e) {
            console.error("NvimGenerator: generate failed:", e);
        }
    }

    // $1 output file, $2 contents. Atomic replace; untouched when unchanged.
    readonly property string script: `
        out="$1"; lua="$2"
        mkdir -p "$(dirname "$out")" || exit 1
        if [ -f "$out" ] && [ "$(cat "$out")" = "$(printf '%s' "$lua")" ]; then exit 0; fi
        printf '%s' "$lua" > "$out.tmp" && mv -f "$out.tmp" "$out"
    `

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("NvimGenerator: Palette generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: err => {
                const text = err ? err.toString().trim() : "";
                if (text)
                    console.error("NvimGenerator Error:", text);
            }
        }
    }
}
