import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.globals
import "ColorUtils.js" as ColorUtils

// Spotify via spicetify: writes the app's theme (color.ini + user.css +
// theme.js) to ~/.config/spicetify/Themes/<app id>. When it is the active theme,
// `spicetify refresh -n` rewrites Spotify's colors.css without restarting it
// and the theme's theme.js swaps the stylesheet live.
QtObject {
    id: root

    readonly property string assetsDir: Quickshell.shellDir + "/assets/spicetify/" + Brand.appId

    function generate(Colors) {
        if (!Colors)
            return;
        try {
            const p = ColorUtils.palette(Colors);
            const hex = c => c.replace("#", "");
            const roles = [
                ["text", p.overSurface],
                ["subtext", p.overSurfaceVariant],
                ["main", p.surfaceContainerLow],
                ["main-elevated", p.surfaceContainer],
                ["sidebar", p.background],
                ["player", p.surfaceContainerHigh],
                ["card", p.surfaceContainer],
                ["shadow", p.shadow],
                ["highlight", p.surfaceContainerHigh],
                ["highlight-elevated", p.surfaceContainerHighest],
                ["selected-row", p.overSurface],
                ["button", p.primary],
                ["button-active", p.primary],
                ["button-disabled", p.outline],
                ["tab-active", p.surfaceContainerHigh],
                ["notification", p.primaryContainer],
                ["notification-error", p.error],
                ["misc", p.outline],
                // Extra roles used by user.css (exposed as --spice-<name>).
                ["on-primary", p.overPrimary],
                ["primary-container", p.primaryContainer],
                ["on-primary-container", p.overPrimaryContainer],
                ["secondary", p.secondary],
                ["secondary-container", p.secondaryContainer],
                ["tertiary", p.tertiary],
                ["outline-variant", p.outlineVariant]
            ];
            let ini = "; Generated by " + Brand.displayName + " from the current Material palette. Do not edit.\n[" + Brand.appId + "]\n";
            for (let i = 0; i < roles.length; i++)
                ini += roles[i][0].padEnd(22, " ") + "= " + hex(roles[i][1]) + "\n";

            writerProcess.command = ["sh", "-c", root.script, Brand.appId + "-spicetify", ini, root.assetsDir, Brand.appId, Brand.legacyAppId];
            writerProcess.running = true;
        } catch (e) {
            console.error("SpicetifyGenerator: generate failed:", e);
        }
    }

    // $1 color.ini contents, $2 bundled theme assets dir, $3 app id,
    // $4 legacy app id. A config whose current theme is the legacy app's is
    // switched to this one (the old theme dir stays) and applied.
    readonly property string script: `
        ini="$1"; assets="$2"; app="$3"; legacy="$4"
        cfgdir="\${XDG_CONFIG_HOME:-$HOME/.config}/spicetify"
        command -v spicetify >/dev/null 2>&1 || [ -d "$cfgdir" ] || exit 0
        dir="$cfgdir/Themes/$app"
        mkdir -p "$dir" || exit 1
        changed=""
        for f in user.css theme.js; do
            [ -f "$assets/$f" ] || continue
            cmp -s "$assets/$f" "$dir/$f" || { cp -f "$assets/$f" "$dir/$f"; changed=1; }
        done
        if ! [ -f "$dir/color.ini" ] || [ "$(cat "$dir/color.ini")" != "$(printf '%s' "$ini")" ]; then
            printf '%s' "$ini" > "$dir/color.ini.tmp" && mv -f "$dir/color.ini.tmp" "$dir/color.ini"
            changed=1
        fi
        conf=""
        command -v spicetify >/dev/null 2>&1 && conf="$(spicetify -c 2>/dev/null)"
        [ -f "$conf" ] || conf="$cfgdir/config-xpui.ini"
        switched=""
        if [ "$legacy" != "$app" ] && grep -Eq "^current_theme[[:space:]]*=[[:space:]]*$legacy[[:space:]]*$" "$conf" 2>/dev/null; then
            sed -E "s/^(current_theme[[:space:]]*=[[:space:]]*)$legacy[[:space:]]*$/\\1$app/; s/^(color_scheme[[:space:]]*=[[:space:]]*)$legacy[[:space:]]*$/\\1$app/" "$conf" > "$conf.tmp" \\
                && mv -f "$conf.tmp" "$conf" && switched=1
        fi
        command -v spicetify >/dev/null 2>&1 || exit 0
        if [ -n "$switched" ]; then
            spicetify -q -n apply >/dev/null 2>&1 || true
        elif [ -n "$changed" ] && grep -Eq "^current_theme[[:space:]]*=[[:space:]]*$app[[:space:]]*$" "$conf" 2>/dev/null; then
            spicetify -q -n refresh >/dev/null 2>&1 || true
        fi
    `

    property Process writerProcess: Process {
        id: writerProcess
        running: false
        stdout: StdioCollector {
            onStreamFinished: console.log("SpicetifyGenerator: Theme generated.")
        }
        stderr: StdioCollector {
            onStreamFinished: err => {
                const text = err ? err.toString().trim() : "";
                if (text)
                    console.error("SpicetifyGenerator Error:", text);
            }
        }
    }
}
