.pragma library
.import "../modules/globals/BrandActions.js" as BrandActions

// Default user binds of binds.json "custom" (compositor actions, editable in
// Settings > Binds), one row each:
//   [name, modifiers, key, dispatcher, argument, flags?]
// binds() expands them to the stored format; the core shell binds live in
// CoreBinds.js.
var ROWS = [
    ["Close Window", ["SUPER"], "Q", "killactive", ""],
    ["Terminal", ["SUPER"], "T", "exec", BrandActions.appId + " run terminal"],
    ["Toggle Floating", ["SUPER"], "SPACE", "togglefloating", ""],
    ["Workspace 1", ["SUPER"], "1", "workspace", "1"],
    ["Workspace 2", ["SUPER"], "2", "workspace", "2"],
    ["Workspace 3", ["SUPER"], "3", "workspace", "3"],
    ["Workspace 4", ["SUPER"], "4", "workspace", "4"],
    ["Workspace 5", ["SUPER"], "5", "workspace", "5"],
    ["Workspace 6", ["SUPER"], "6", "workspace", "6"],
    ["Workspace 7", ["SUPER"], "7", "workspace", "7"],
    ["Workspace 8", ["SUPER"], "8", "workspace", "8"],
    ["Workspace 9", ["SUPER"], "9", "workspace", "9"],
    ["Workspace 10", ["SUPER"], "0", "workspace", "10"],
    ["Move Window to Workspace 1", ["SUPER", "SHIFT"], "1", "movetoworkspace", "1"],
    ["Move Window to Workspace 2", ["SUPER", "SHIFT"], "2", "movetoworkspace", "2"],
    ["Move Window to Workspace 3", ["SUPER", "SHIFT"], "3", "movetoworkspace", "3"],
    ["Move Window to Workspace 4", ["SUPER", "SHIFT"], "4", "movetoworkspace", "4"],
    ["Move Window to Workspace 5", ["SUPER", "SHIFT"], "5", "movetoworkspace", "5"],
    ["Move Window to Workspace 6", ["SUPER", "SHIFT"], "6", "movetoworkspace", "6"],
    ["Move Window to Workspace 7", ["SUPER", "SHIFT"], "7", "movetoworkspace", "7"],
    ["Move Window to Workspace 8", ["SUPER", "SHIFT"], "8", "movetoworkspace", "8"],
    ["Move Window to Workspace 9", ["SUPER", "SHIFT"], "9", "movetoworkspace", "9"],
    ["Move Window to Workspace 10", ["SUPER", "SHIFT"], "0", "movetoworkspace", "10"],
    ["Move Window Silently to Workspace 1", ["SUPER", "ALT"], "1", "movetoworkspacesilent", "1"],
    ["Move Window Silently to Workspace 2", ["SUPER", "ALT"], "2", "movetoworkspacesilent", "2"],
    ["Move Window Silently to Workspace 3", ["SUPER", "ALT"], "3", "movetoworkspacesilent", "3"],
    ["Move Window Silently to Workspace 4", ["SUPER", "ALT"], "4", "movetoworkspacesilent", "4"],
    ["Move Window Silently to Workspace 5", ["SUPER", "ALT"], "5", "movetoworkspacesilent", "5"],
    ["Move Window Silently to Workspace 6", ["SUPER", "ALT"], "6", "movetoworkspacesilent", "6"],
    ["Move Window Silently to Workspace 7", ["SUPER", "ALT"], "7", "movetoworkspacesilent", "7"],
    ["Move Window Silently to Workspace 8", ["SUPER", "ALT"], "8", "movetoworkspacesilent", "8"],
    ["Move Window Silently to Workspace 9", ["SUPER", "ALT"], "9", "movetoworkspacesilent", "9"],
    ["Move Window Silently to Workspace 10", ["SUPER", "ALT"], "0", "movetoworkspacesilent", "10"],
    ["Switch Occupied Workspace -1", ["SUPER"], "mouse_down", "workspace", "e-1"],
    ["Switch Occupied Workspace +1", ["SUPER"], "mouse_up", "workspace", "e+1"],
    ["Switch Occupied Workspace -1", ["SUPER", "SHIFT"], "Z", "workspace", "e-1"],
    ["Switch Occupied Workspace +1", ["SUPER", "SHIFT"], "X", "workspace", "e+1"],
    ["Switch Relative Workspace -1", ["SUPER"], "Z", "workspace", "-1"],
    ["Switch Relative Workspace +1", ["SUPER"], "X", "workspace", "+1"],
    ["Drag Window", ["SUPER"], "mouse:272", "movewindow", "", "m"],
    ["Resize Window with Mouse", ["SUPER"], "mouse:273", "resizewindow", "", "m"],
    ["Media Play Pause", [], "XF86AudioPlay", "exec", "playerctl play-pause"],
    ["Media Previous", [], "XF86AudioPrev", "exec", "playerctl previous"],
    ["Media Next", [], "XF86AudioNext", "exec", "playerctl next"],
    ["Media Play Pause", [], "XF86AudioMedia", "exec", "playerctl play-pause", "l"],
    ["Media Stop", [], "XF86AudioStop", "exec", "playerctl stop", "l"],
    ["Volume Up", [], "XF86AudioRaiseVolume", "exec", "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%+", "le"],
    ["Volume Down", [], "XF86AudioLowerVolume", "exec", "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%-", "le"],
    ["Mute Audio", [], "XF86AudioMute", "exec", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle", "le"],
    ["Brightness Up", [], "XF86MonBrightnessUp", "exec", "sh -c 'echo brightness-up > \"${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/" + BrandActions.appId + "_ipc.pipe\"'", "le"],
    ["Brightness Down", [], "XF86MonBrightnessDown", "exec", "sh -c 'echo brightness-down > \"${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/" + BrandActions.appId + "_ipc.pipe\"'", "le"],
    ["Calculator", [], "XF86Calculator", "exec", "notify-send \"Soon\""],
    ["Toggle Special Workspace", ["SUPER", "SHIFT"], "V", "togglespecialworkspace", ""],
    ["Move Window to Special Workspace", ["SUPER", "ALT"], "V", "movetoworkspace", "special"],
    ["Lock Session on Lid Switch", [], "switch:Lid Switch", "exec", "loginctl lock-session", "l"],
    ["Display Off on Lid Close", [], "switch:on:Lid Switch", "exec", BrandActions.daemonCommand("monitor", "set-dpms", "0", "0"), "l"],
    ["Display On on Lid Open", [], "switch:off:Lid Switch", "exec", BrandActions.daemonCommand("monitor", "set-dpms", "0", "1"), "l"],
    ["Focus Up", ["SUPER"], "Up", "movefocus", "u"],
    ["Focus Up", ["SUPER", "CTRL"], "k", "movefocus", "u"],
    ["Focus Down", ["SUPER"], "Down", "movefocus", "d"],
    ["Focus Down", ["SUPER", "CTRL"], "j", "movefocus", "d"],
    ["Focus Left", ["SUPER"], "Left", "movefocus", "l"],
    ["Focus Left", ["SUPER", "CTRL"], "z", "movefocus", "l"],
    ["Focus Left", ["SUPER", "CTRL"], "h", "movefocus", "l"],
    ["Focus Right", ["SUPER"], "Right", "movefocus", "r"],
    ["Focus Right", ["SUPER", "CTRL"], "x", "movefocus", "r"],
    ["Focus Right", ["SUPER", "CTRL"], "l", "movefocus", "r"],
    ["Move Window Left", ["SUPER", "SHIFT"], "Left", "movewindow", "l"],
    ["Move Window Left", ["SUPER", "SHIFT"], "h", "movewindow", "l"],
    ["Move Window Right", ["SUPER", "SHIFT"], "Right", "movewindow", "r"],
    ["Move Window Right", ["SUPER", "SHIFT"], "l", "movewindow", "r"],
    ["Move Window Up", ["SUPER", "SHIFT"], "Up", "movewindow", "u"],
    ["Move Window Up", ["SUPER", "SHIFT"], "k", "movewindow", "u"],
    ["Move Window Down", ["SUPER", "SHIFT"], "Down", "movewindow", "d"],
    ["Move Window Down", ["SUPER", "SHIFT"], "j", "movewindow", "d"],
    ["Resize Column +0.1", ["SUPER", "ALT"], "Right", "layoutmsg", "colresize +0.1"],
    ["Resize Column +0.1", ["SUPER", "ALT"], "l", "layoutmsg", "colresize +0.1"],
    ["Resize Column -0.1", ["SUPER", "ALT"], "Left", "layoutmsg", "colresize -0.1"],
    ["Resize Column -0.1", ["SUPER", "ALT"], "h", "layoutmsg", "colresize -0.1"],
    ["Resize Active 0 50", ["SUPER", "ALT"], "Down", "resizeactive", "0 50"],
    ["Resize Active 0 50", ["SUPER", "ALT"], "j", "resizeactive", "0 50"],
    ["Resize Active 0 -50", ["SUPER", "ALT"], "Up", "resizeactive", "0 -50"],
    ["Resize Active 0 -50", ["SUPER", "ALT"], "k", "resizeactive", "0 -50"],
    ["Promote Column", ["SUPER", "ALT"], "SPACE", "layoutmsg", "promote"],
    ["Toggle Fit", ["SUPER", "CTRL"], "SPACE", "layoutmsg", "togglefit"],
    ["Resize Column +conf", ["SUPER", "SHIFT"], "SPACE", "layoutmsg", "colresize +conf"],
    ["Swap Column Left", ["SUPER", "ALT", "CTRL"], "Left", "layoutmsg", "swapcol l"],
    ["Swap Column Left", ["SUPER", "ALT", "CTRL"], "h", "layoutmsg", "swapcol l"],
    ["Swap Column Right", ["SUPER", "ALT", "CTRL"], "Right", "layoutmsg", "swapcol r"],
    ["Swap Column Right", ["SUPER", "ALT", "CTRL"], "l", "layoutmsg", "swapcol r"],
    ["Move Column to Workspace 1", ["SUPER", "CTRL", "ALT"], "1", "layoutmsg", "movecoltoworkspace 1"],
    ["Move Column to Workspace 2", ["SUPER", "CTRL", "ALT"], "2", "layoutmsg", "movecoltoworkspace 2"],
    ["Move Column to Workspace 3", ["SUPER", "CTRL", "ALT"], "3", "layoutmsg", "movecoltoworkspace 3"],
    ["Move Column to Workspace 4", ["SUPER", "CTRL", "ALT"], "4", "layoutmsg", "movecoltoworkspace 4"],
    ["Move Column to Workspace 5", ["SUPER", "CTRL", "ALT"], "5", "layoutmsg", "movecoltoworkspace 5"],
    ["Move Column to Workspace 6", ["SUPER", "CTRL", "ALT"], "6", "layoutmsg", "movecoltoworkspace 6"],
    ["Move Column to Workspace 7", ["SUPER", "CTRL", "ALT"], "7", "layoutmsg", "movecoltoworkspace 7"],
    ["Move Column to Workspace 8", ["SUPER", "CTRL", "ALT"], "8", "layoutmsg", "movecoltoworkspace 8"],
    ["Move Column to Workspace 9", ["SUPER", "CTRL", "ALT"], "9", "layoutmsg", "movecoltoworkspace 9"],
    ["Move Column to Workspace 10", ["SUPER", "CTRL", "ALT"], "0", "layoutmsg", "movecoltoworkspace 10"],
    ["AI Quick Ask", ["SUPER", "ALT"], "A", "exec", BrandActions.appId + " run ai-quickask"],
    ["AI Selection Actions", ["SUPER", "ALT"], "S", "exec", BrandActions.appId + " run ai-selection"],
    ["AI Ask About Region", ["SUPER", "ALT"], "R", "exec", BrandActions.appId + " run ai-region"]
];

function binds() {
    return ROWS.map(function (r) {
        return {
            "name": r[0],
            "keys": [{
                    "modifiers": r[1].slice(),
                    "key": r[2]
                }],
            "actions": [{
                    "dispatcher": r[3],
                    "argument": r[4],
                    "flags": r[5] || "",
                    "layouts": []
                }],
            "enabled": true
        };
    });
}
