package termlook

import (
	"fmt"
	"strings"

	"yozakura/backend/pkg/brand"
)

// starshipVars is the variable part of each module's format (icons, prefix
// and colors are added around it).
var starshipVars = map[string]string{
	"os":         "$symbol",
	"user":       "$user",
	"host":       "$hostname",
	"dir":        "$path$read_only",
	"git_branch": "$branch",
	"git_status": "$all_status$ahead_behind",
	"duration":   "$duration",
	"time":       "$time",
	"status":     "$status",
	"jobs":       "$number",
	"battery":    "$symbol$percentage",
	"langs":      "$version",
}

var starshipModules = map[string]string{
	"os": "os", "user": "username", "host": "hostname", "dir": "directory",
	"git_branch": "git_branch", "git_status": "git_status", "duration": "cmd_duration",
	"time": "time", "status": "status", "jobs": "jobs", "battery": "battery",
}

// RenderStarship renders a full starship.toml for the preset, colors taken
// from a [palettes.<app>] table so a theme change only rewrites values.
func RenderStarship(p Preset, pal Palette) string {
	r := starshipRenderer{p: p, sep: SeparatorGlyphs[p.Separator]}
	var format strings.Builder
	if p.Frame {
		format.WriteString(fmt.Sprintf("[%s](fg:outline) ", frameTop))
	}
	for i, s := range p.Left {
		format.WriteString(r.segment(s, i == 0, true, joinsPrevious(p, p.Left, i)))
	}
	if p.Layout == "powerline" {
		format.WriteString(fmt.Sprintf("[%s](fg:prev_bg) ", r.sep[0]))
	}
	var right strings.Builder
	for i, s := range p.Right {
		right.WriteString(r.segment(s, i == 0, false, joinsPrevious(p, p.Right, i)))
	}
	if p.Layout == "powerline" && p.Separator == "rounded" && len(p.Right) > 0 {
		right.WriteString(fmt.Sprintf("[%s](fg:prev_bg)", r.sep[0]))
	}
	rightFormat := right.String()
	if p.Lines == 2 {
		if rightFormat != "" {
			format.WriteString("$fill" + rightFormat)
			rightFormat = ""
		}
		format.WriteString("$line_break")
		if p.Frame {
			format.WriteString(fmt.Sprintf("[%s](fg:outline)", frameBottom))
		}
	}
	format.WriteString("$character")

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by %s from the %q prompt preset; regenerated on theme change.\n", brand.DisplayName, p.ID)
	b.WriteString("\"$schema\" = 'https://starship.rs/config-schema.json'\n\n")
	fmt.Fprintf(&b, "add_newline = %t\n", p.Lines == 2)
	fmt.Fprintf(&b, "palette = %s\n", tomlString(brand.AppID))
	fmt.Fprintf(&b, "format = %s\n", tomlString(format.String()))
	if rightFormat != "" {
		fmt.Fprintf(&b, "right_format = %s\n", tomlString(rightFormat))
	}
	fmt.Fprintf(&b, "\n[palettes.%s]\n", brand.AppID)
	for _, role := range Roles {
		fmt.Fprintf(&b, "%s = %s\n", paletteKey(role), tomlString(pal[role]))
	}
	b.WriteString(r.tables.String())
	if p.Lines == 2 && len(p.Right) > 0 {
		b.WriteString("\n[fill]\nsymbol = \" \"\n")
	}
	b.WriteString("\n[character]\nformat = \"$symbol \"\n")
	fmt.Fprintf(&b, "success_symbol = %s\n", tomlString(charFormat(p.Char.Symbol, p.Char.Color)))
	fmt.Fprintf(&b, "error_symbol = %s\n", tomlString(charFormat(p.Char.Error, "error")))
	fmt.Fprintf(&b, "vimcmd_symbol = %s\n", tomlString(charFormat(p.Char.Symbol, "secondary")))
	return b.String()
}

type starshipRenderer struct {
	p      Preset
	sep    [2]string
	tables strings.Builder
}

func charFormat(symbol, role string) string {
	return fmt.Sprintf("[%s](bold fg:%s)", fmtLit(symbol), paletteKey(role))
}

// segment emits the module table(s) for s and returns its main-format
// variables. Separators live inside each module's own format so a hidden
// module (no git repo, no error) takes its separator with it; prev_bg
// joins whichever module rendered last.
func (r *starshipRenderer) segment(s Segment, first, left, joined bool) string {
	if s.Type == "langs" {
		var vars strings.Builder
		for i, l := range langs {
			icon := ""
			if r.p.NerdFont {
				icon = l.icon
			}
			r.module(l.starship, s, r.wrap(s, icon, first, left, joined && i == 0), nil)
			vars.WriteString("$" + l.starship)
		}
		return vars.String()
	}
	mod := starshipModules[s.Type]
	r.module(mod, s, r.wrap(s, segmentIcon(r.p, s), first, left, joined), r.extras(s.Type))
	return "$" + mod
}

// joinsPrevious reports a powerline segment that continues the previous
// one's background with no separator: same background, and the previous
// segment is always visible whenever this one is (so prev_bg is known).
func joinsPrevious(p Preset, segs []Segment, i int) bool {
	if p.Layout != "powerline" || i == 0 || segs[i-1].BG != segs[i].BG {
		return false
	}
	prev := segs[i-1].Type
	return alwaysShown[prev] || (prev == "git_branch" && segs[i].Type == "git_status")
}

// wrap builds a module format: separator/caps + colored body. joined skips
// the separator (same background as the segment before).
func (r *starshipRenderer) wrap(s Segment, icon string, first, left, joined bool) string {
	body := starshipVars[s.Type]
	if icon != "" {
		body = fmtLit(icon) + " " + body
	}
	style := s.Style
	if style != "" {
		style += " "
	}
	style += "fg:" + paletteKey(s.FG)
	var out string
	switch r.p.Layout {
	case "text":
		if r.p.Separator != "none" && !first {
			out = fmt.Sprintf("[%s ](fg:outline)", r.sep[0])
		}
		if s.Prefix != "" {
			out += fmt.Sprintf("[%s](fg:outline)", fmtLit(s.Prefix))
		}
		out += fmt.Sprintf("[%s](%s)", body, style)
		if s.Suffix != "" {
			out += fmt.Sprintf("[%s](fg:outline)", fmtLit(s.Suffix))
		}
		if left {
			out += " "
		} else {
			out = " " + out
		}
	case "pills":
		bg := paletteKey(s.BG)
		out = fmt.Sprintf("[%s](fg:%s)[%s%s%s](%s bg:%s)[%s](fg:%s)", r.sep[1], bg,
			fmtLit(s.Prefix), body, fmtLit(s.Suffix), style, bg, r.sep[0], bg)
		if left {
			out += " "
		} else {
			out = " " + out
		}
	default: // powerline
		bg := paletteKey(s.BG)
		switch {
		case joined:
		case !left:
			out = fmt.Sprintf("[%s](fg:%s bg:prev_bg)", r.sep[1], bg)
		case !first:
			out = fmt.Sprintf("[%s](fg:prev_bg bg:%s)", r.sep[0], bg)
		case r.p.Separator == "rounded":
			out = fmt.Sprintf("[%s](fg:%s)", r.sep[1], bg)
		}
		out += fmt.Sprintf("[ %s%s%s ](%s bg:%s)", fmtLit(s.Prefix), body, fmtLit(s.Suffix), style, bg)
	}
	if s.Type == "git_status" {
		// Conditional group: only drawn when a status variable is non-empty.
		out = "(" + out + ")"
	}
	return out
}

func (r *starshipRenderer) module(name string, s Segment, format string, extras []string) {
	fmt.Fprintf(&r.tables, "\n[%s]\n", name)
	switch s.Type {
	case "os", "time", "status":
		r.tables.WriteString("disabled = false\n")
	}
	fmt.Fprintf(&r.tables, "format = %s\n", tomlString(format))
	for _, e := range extras {
		r.tables.WriteString(e + "\n")
	}
}

// extras are per-module settings beyond the format.
func (r *starshipRenderer) extras(typ string) []string {
	nf := r.p.NerdFont
	switch typ {
	case "user":
		return []string{"show_always = true"}
	case "host":
		return []string{"ssh_only = false"}
	case "dir":
		lock := " ro"
		if nf {
			lock = readOnlyLock
		}
		return []string{"truncation_length = 3", "truncation_symbol = \"…/\"", "read_only = " + tomlString(lock)}
	case "duration":
		return []string{"min_time = 2000"}
	case "time":
		return []string{"time_format = \"%H:%M\""}
	case "jobs":
		return []string{"symbol_threshold = 1", "number_threshold = 1"}
	case "os":
		if !nf {
			return nil
		}
		out := []string{"\n[os.symbols]"}
		for _, s := range osSymbols {
			out = append(out, fmt.Sprintf("%s = %s", s[0], tomlString(s[1])))
		}
		return out
	case "battery":
		out := []string{}
		if nf {
			out = append(out, "full_symbol = "+tomlString(batteryFull), "charging_symbol = "+tomlString(batteryCharging),
				"discharging_symbol = "+tomlString(batteryDischarging), "empty_symbol = "+tomlString(batteryEmpty))
		}
		return append(out, "\n[[battery.display]]", "threshold = 30")
	}
	return nil
}

// fmtLit escapes literal text for a starship format string.
func fmtLit(s string) string {
	var b strings.Builder
	for _, r := range s {
		if strings.ContainsRune(`\[]()$`, r) {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// tomlString quotes s as a TOML basic string; Private-Use glyphs become
// \u escapes so generated files stay readable and diffable.
func tomlString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r < 0x20 || r == 0x7f:
			fmt.Fprintf(&b, "\\u%04X", r)
		case isPUA(r) && r > 0xFFFF:
			fmt.Fprintf(&b, "\\U%08X", r)
		case isPUA(r):
			fmt.Fprintf(&b, "\\u%04X", r)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
