// Builds the keybind action catalog assets/schema/bind-actions.json for the
// Go bind advisor (backend/pkg/binds: `yozakura binds`, MCP binds_* tools)
// from config/KeybindActions.js (ids, groups, dispatchers, argument fields),
// config/CoreBinds.js (the shell's own binds and their defaults) and the
// binds.action.* / binds.group.* / binds.field.* translations of every
// language. Pure: build(repo) returns the object; gen_schema.cjs writes it.
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const FILE = 'bind-actions.json';

function translations(repo) {
    const dir = path.join(repo, 'translations');
    const out = {};
    for (const f of fs.readdirSync(dir).sort()) {
        if (!f.endsWith('.json') || f === 'languages.json') continue;
        out[f.slice(0, -5)] = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
    }
    return out;
}

// {lang: text} of a translation key, languages without it left out.
function labels(tr, key, fallback) {
    const out = {};
    for (const lang of Object.keys(tr)) {
        const v = tr[lang][key];
        if (typeof v === 'string' && v) out[lang] = v;
    }
    if (!out.en && fallback) out.en = fallback;
    return out;
}

function build(repo) {
    const { loadLibrary } = require(path.join(repo, 'tests/lib/qmljs.cjs'));
    const cache = new Map();
    const lib = rel => loadLibrary(path.join(repo, rel), cache);
    const Actions = lib('config/KeybindActions.js');
    const Core = lib('config/CoreBinds.js');
    const tr = translations(repo);

    const groups = [];
    const seenGroups = new Set();
    const actions = Actions.ACTION_CATALOG.map(a => {
        if (!seenGroups.has(a.group)) {
            seenGroups.add(a.group);
            groups.push({ id: a.group, labels: labels(tr, 'binds.group.' + a.group, a.group), descriptions: labels(tr, 'binds.group.' + a.group + '.desc') });
        }
        const out = {
            id: a.id,
            labels: labels(tr, Actions.labelKey(a.id), a.label),
            category: a.category,
            group: a.group,
            dispatcher: a.dispatcher || '',
        };
        // A static argument only: argumentBuilder actions depend on args.
        if (!a.argumentBuilder && a.argument !== undefined) out.argument = a.argument;
        if (a.flags) out.flags = a.flags;
        if (a.hold) out.hold = true;
        if (a.hidden) out.hidden = true;
        if (a.slot) out.slot = true;
        if (a.args) {
            out.args = a.args.map(f => ({
                key: f.key,
                labels: labels(tr, Actions.fieldLabelKey(f.key), f.label),
                placeholder: f.placeholder || '',
                kind: f.kind || 'text',
                default: f.defaultValue !== undefined ? String(f.defaultValue) : '',
            }));
        }
        return out;
    });
    const core = Core.BINDS.map(b => ({
        path: Core.path(b),
        modifiers: b.modifiers.slice(),
        key: b.key,
        action: Core.actionId(b),
    }));
    // Plain objects: the libraries run in their own vm realm.
    return JSON.parse(JSON.stringify({
        _doc: 'Keybind action catalog for the bind advisor. Generated by tools/schema/gen_schema.cjs (make schema) from config/KeybindActions.js, config/CoreBinds.js and translations/*.json - do not edit.',
        version: 1,
        groups,
        actions,
        core,
    }));
}

module.exports = { build, FILE };
