"""Count-based finding baselines, robust to line shifts.

A finding is reduced to a *fingerprint* that does not contain line numbers
(e.g. rule id + message + the stripped source line). The baseline stores how
many times each fingerprint occurred per file. A run fails only when a
fingerprint occurs MORE often than recorded, so moving code around is fine,
while any new occurrence (in any file, including cross-file regressions such
as a removed property breaking a caller) is reported.
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from common import REPO, fail, info, ok


@dataclass
class Finding:
    file: str  # repo-relative path
    line: int
    column: int
    rule: str
    message: str
    fingerprint: str
    severity: str = "warning"

    def render(self) -> str:
        loc = f"{self.file}:{self.line}:{self.column}" if self.line else self.file
        return f"{loc}: {self.message} [{self.rule}]"


@dataclass
class Result:
    new: list[Finding] = field(default_factory=list)
    fixed: int = 0
    total: int = 0
    baselined: int = 0


def group(findings: list[Finding]) -> dict[str, Counter]:
    out: dict[str, Counter] = defaultdict(Counter)
    for f in findings:
        out[f.file][f.fingerprint] += 1
    return out


def load(path: Path) -> dict[str, Counter]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text())
    return {f: Counter(fps) for f, fps in data.get("files", {}).items()}


def save(path: Path, tool: str, findings: list[Finding], keep_files: dict[str, Counter] | None = None) -> None:
    """Write the baseline. `keep_files` preserves entries for files not linted in this run."""
    grouped = dict(keep_files or {})
    grouped.update(group(findings))
    files = {f: dict(sorted(c.items())) for f, c in sorted(grouped.items()) if c}
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "tool": tool,
        "note": "Generated by `make baseline`. Existing findings only; never add new ones by hand.",
        "total": sum(sum(c.values()) for c in files.values()),
        "files": files,
    }
    path.write_text(json.dumps(payload, indent=1, ensure_ascii=False, sort_keys=False) + "\n")


def compare(findings: list[Finding], baseline: dict[str, Counter], files: set[str] | None = None) -> Result:
    """Compare findings to the baseline; `files` limits the comparison scope."""
    current = group(findings)
    res = Result(total=len(findings))
    by_fp: dict[tuple[str, str], list[Finding]] = defaultdict(list)
    for f in findings:
        by_fp[(f.file, f.fingerprint)].append(f)
    for file, counter in current.items():
        base = baseline.get(file, Counter())
        for fp, n in counter.items():
            allowed = base.get(fp, 0)
            res.baselined += min(n, allowed)
            if n > allowed:
                occurrences = by_fp[(file, fp)]
                # Cannot tell which occurrence is new; report the trailing ones.
                res.new.extend(occurrences[allowed:] if allowed else occurrences)
    for file, counter in baseline.items():
        if files is not None and file not in files:
            continue
        cur = current.get(file, Counter())
        for fp, n in counter.items():
            res.fixed += max(0, n - cur.get(fp, 0))
    return res


def report(tool: str, res: Result, baseline_path: Path, limit: int = 200) -> int:
    rel = baseline_path.relative_to(REPO)
    if res.new:
        for f in res.new[:limit]:
            print(f"  {f.render()}")
        if len(res.new) > limit:
            print(f"  ... and {len(res.new) - limit} more")
        fail(f"{tool}: {len(res.new)} new finding(s) not in {rel} "
             f"({res.baselined} baselined)")
        info("  Fix them. Only if a finding is a tool false positive, refresh the baseline "
             "with `make baseline` and justify it in the commit message.")
        return 1
    msg = f"{tool}: no new findings ({res.baselined} baselined)"
    if res.fixed:
        msg += f"; {res.fixed} baselined finding(s) fixed - run `make baseline` to ratchet"
    ok(msg)
    return 0
