// Generated by tools/config/gen_adapters.cjs from config/defaults/ai.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: true
    property string systemPrompt: "You are a helpful assistant running on a Linux system. You have access to some tools to control the system."
    property string tool: "none"
    property list<var> extraModels: []
    property string defaultModel: ""
    property int sidebarWidth: 400
    property string sidebarPosition: "right"
    property bool sidebarPinnedOnStartup: false
    property int wideWidth: 1040
    property string defaultMode: "chat"
    property bool showThinking: true
    property bool chatTools: true
    property int maxToolRounds: 8
    property int unloadAfterMinutes: 10
    property JsonObject agents: JsonObject {
        property string defaultAgent: "claude"
        property string defaultCwd: ""
        property list<var> recentDirs: []
        property list<var> autoApprove: ["read"]
        property JsonObject claude: JsonObject {
            property bool enabled: true
            property string binary: ""
            property string model: ""
            property string effort: ""
            property bool yolo: false
            property list<var> extraArgs: []
        }
        property JsonObject codex: JsonObject {
            property bool enabled: true
            property string binary: ""
            property string model: ""
            property string effort: ""
            property bool yolo: false
            property list<var> extraArgs: []
        }
        property JsonObject opencode: JsonObject {
            property bool enabled: true
            property string binary: ""
            property string model: ""
            property string effort: ""
            property bool yolo: false
            property list<var> extraArgs: []
        }
    }
    property JsonObject mcp: JsonObject {
        property bool yozakura: true
        property bool importClaude: true
        property bool importCodex: true
        property bool importOpencode: true
        property list<var> disabled: []
    }
    property JsonObject shell: JsonObject {
        property bool enabled: true
        property string target: ""
        property string systemPrompt: "You control the user's Yozakura desktop shell through the yozakura MCP tools (config, presets, wallpaper, windows, workspaces, notifications, clipboard, screenshots, media, do-not-disturb). Inspect state with the read-only tools first, then make the smallest change that fulfils the request and say what you changed in one sentence."
    }
    property JsonObject quickAsk: JsonObject {
        property bool enabled: true
        property string model: ""
        property int width: 560
    }
    property JsonObject selection: JsonObject {
        property bool enabled: true
        property string language: "English"
        property string output: "replace"
        property list<var> actions: [
            {
                "id": "translate",
                "label": "",
                "icon": "translate",
                "output": "",
                "prompt": "Translate the text below to {language}. If it already is {language}, translate it to Spanish. Reply with the translation only, keeping formatting.\n\n{selection}"
            },
            {
                "id": "explain",
                "label": "",
                "icon": "lightbulb",
                "output": "sidebar",
                "prompt": "Explain the following clearly and briefly:\n\n{selection}"
            },
            {
                "id": "rewrite",
                "label": "",
                "icon": "magicWand",
                "output": "",
                "prompt": "Rewrite the text below to be clearer and more natural, same language and meaning. Reply with the rewritten text only.\n\n{selection}"
            },
            {
                "id": "fix",
                "label": "",
                "icon": "bug",
                "output": "",
                "prompt": "Fix bugs and obvious mistakes in this code. Reply with the corrected code only, no fences, no commentary.\n\n{selection}"
            },
            {
                "id": "summarize",
                "label": "",
                "icon": "list",
                "output": "sidebar",
                "prompt": "Summarize in 3 bullet points:\n\n{selection}"
            }
        ]
    }
    property list<var> prompts: [
        {
            "id": "briefing",
            "name": "Morning briefing",
            "prompt": "Today is {date}. Give me a short, upbeat morning briefing: a focus suggestion for the day and one tip about my Linux desktop.",
            "output": "notify"
        },
        {
            "id": "explain-error",
            "name": "Explain error",
            "prompt": "Explain this error and how to fix it, briefly:\n\n{clipboard}",
            "output": "sidebar"
        },
        {
            "id": "commit-msg",
            "name": "Commit message",
            "prompt": "Write a conventional commit message for this diff:\n\n{clipboard}",
            "output": "clipboard"
        }
    ]
    property list<var> automations: [
        {
            "id": "morning",
            "name": "Morning briefing",
            "enabled": false,
            "trigger": {
                "type": "login",
                "cron": "",
                "pattern": "",
                "kinds": []
            },
            "prompt": "Today is {date}. Give me a short, upbeat morning briefing: a focus suggestion for the day and one tip about my Linux desktop.",
            "model": "",
            "output": "notify",
            "offer": false
        },
        {
            "id": "stacktrace",
            "name": "Explain copied errors",
            "enabled": false,
            "trigger": {
                "type": "clipboard",
                "cron": "",
                "pattern": "(Traceback \\(most recent call last\\)|Exception in thread|panic: |error\\[E\\d+\\]|at .+\\(.+:\\d+:\\d+\\)|Segmentation fault)",
                "kinds": []
            },
            "prompt": "Explain this error and how to fix it, briefly:\n\n{clipboard}",
            "model": "",
            "output": "sidebar",
            "offer": true
        },
        {
            "id": "download-done",
            "name": "Summarize finished downloads",
            "enabled": false,
            "trigger": {
                "type": "transfer",
                "cron": "",
                "pattern": "",
                "kinds": ["download"]
            },
            "prompt": "A download just finished: {input}. In one sentence, tell me what it probably is and what to do next.",
            "model": "",
            "output": "notify",
            "offer": false
        },
        {
            "id": "screenshot-ocr",
            "name": "Describe screenshots",
            "enabled": false,
            "trigger": {
                "type": "screenshot",
                "cron": "",
                "pattern": "",
                "kinds": []
            },
            "prompt": "Describe this screenshot in one short paragraph.",
            "model": "",
            "output": "notify",
            "offer": true
        }
    ]
    property JsonObject voice: JsonObject {
        property bool enabled: true
    }
}
