// Generated by tools/config/gen_adapters.cjs from config/defaults/ai.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: true
    property string systemPrompt: "You are the user's assistant on their Linux desktop (Yozakura). You can control the desktop shell through the yozakura tools (config, presets, wallpaper, windows, workspaces, notifications, clipboard, screenshots, media, do-not-disturb): inspect state with the read-only tools first, make the smallest change that fulfils a request and say what you changed in one sentence. Otherwise answer clearly and briefly."
    property list<var> extraModels: []
    property string defaultModel: ""
    property int sidebarWidth: 400
    property string sidebarPosition: "right"
    property bool sidebarPinnedOnStartup: false
    property int wideWidth: 1040
    property bool showThinking: true
    property bool chatTools: true
    property int maxToolRounds: 8
    property int unloadAfterMinutes: 10
    property JsonObject agents: JsonObject {
        property string defaultAgent: "claude"
        property string defaultCwd: ""
        property list<var> recentDirs: []
        property list<var> autoApprove: ["read"]
        property JsonObject claude: JsonObject {
            property bool enabled: true
            property string binary: ""
            property string model: ""
            property string effort: ""
            property bool yolo: false
            property list<var> extraArgs: []
        }
        property JsonObject codex: JsonObject {
            property bool enabled: true
            property string binary: ""
            property string model: ""
            property string effort: ""
            property bool yolo: false
            property list<var> extraArgs: []
        }
        property JsonObject opencode: JsonObject {
            property bool enabled: true
            property string binary: ""
            property string model: ""
            property string effort: ""
            property bool yolo: false
            property list<var> extraArgs: []
        }
    }
    property JsonObject mcp: JsonObject {
        property bool yozakura: true
        property bool importClaude: true
        property bool importCodex: true
        property bool importOpencode: true
        property list<var> disabled: []
    }
    property JsonObject quickAsk: JsonObject {
        property bool enabled: true
        property string model: ""
        property int width: 560
    }
    property JsonObject selection: JsonObject {
        property bool enabled: true
        property string language: "English"
        property string output: "replace"
        property list<var> actions: [
            {
                "id": "translate",
                "label": "",
                "icon": "translate",
                "output": "",
                "prompt": "Translate the text below to {language}. If it already is {language}, translate it to Spanish. Reply with the translation only, keeping formatting.\n\n{selection}"
            },
            {
                "id": "explain",
                "label": "",
                "icon": "lightbulb",
                "output": "sidebar",
                "prompt": "Explain the following clearly and briefly:\n\n{selection}"
            },
            {
                "id": "rewrite",
                "label": "",
                "icon": "magicWand",
                "output": "",
                "prompt": "Rewrite the text below to be clearer and more natural, same language and meaning. Reply with the rewritten text only.\n\n{selection}"
            },
            {
                "id": "fix",
                "label": "",
                "icon": "bug",
                "output": "",
                "prompt": "Fix bugs and obvious mistakes in this code. Reply with the corrected code only, no fences, no commentary.\n\n{selection}"
            },
            {
                "id": "summarize",
                "label": "",
                "icon": "list",
                "output": "sidebar",
                "prompt": "Summarize in 3 bullet points:\n\n{selection}"
            }
        ]
    }
    property list<var> prompts: [
        {
            "id": "briefing",
            "name": "Morning briefing",
            "prompt": "Today is {date}. Give me a short, upbeat morning briefing: a focus suggestion for the day and one tip about my Linux desktop.",
            "output": "notify"
        },
        {
            "id": "explain-error",
            "name": "Explain error",
            "prompt": "Explain this error and how to fix it, briefly:\n\n{clipboard}",
            "output": "sidebar"
        },
        {
            "id": "commit-msg",
            "name": "Commit message",
            "prompt": "Write a conventional commit message for this diff:\n\n{clipboard}",
            "output": "clipboard"
        }
    ]
    property list<var> automations: [
        {
            "id": "morning",
            "name": "Morning briefing",
            "enabled": false,
            "trigger": {
                "type": "login",
                "cron": "",
                "pattern": "",
                "kinds": []
            },
            "prompt": "Today is {date}. Give me a short, upbeat morning briefing: a focus suggestion for the day and one tip about my Linux desktop.",
            "model": "",
            "output": "notify",
            "offer": false
        },
        {
            "id": "stacktrace",
            "name": "Explain copied errors",
            "enabled": false,
            "trigger": {
                "type": "clipboard",
                "cron": "",
                "pattern": "(Traceback \\(most recent call last\\)|Exception in thread|panic: |error\\[E\\d+\\]|at .+\\(.+:\\d+:\\d+\\)|Segmentation fault)",
                "kinds": []
            },
            "prompt": "Explain this error and how to fix it, briefly:\n\n{clipboard}",
            "model": "",
            "output": "sidebar",
            "offer": true
        },
        {
            "id": "download-done",
            "name": "Summarize finished downloads",
            "enabled": false,
            "trigger": {
                "type": "transfer",
                "cron": "",
                "pattern": "",
                "kinds": ["download"]
            },
            "prompt": "A download just finished: {input}. In one sentence, tell me what it probably is and what to do next.",
            "model": "",
            "output": "notify",
            "offer": false
        },
        {
            "id": "screenshot-ocr",
            "name": "Describe screenshots",
            "enabled": false,
            "trigger": {
                "type": "screenshot",
                "cron": "",
                "pattern": "",
                "kinds": []
            },
            "prompt": "Describe this screenshot in one short paragraph.",
            "model": "",
            "output": "notify",
            "offer": true
        }
    ]
    property JsonObject voice: JsonObject {
        property bool enabled: true
    }
    property JsonObject appearance: JsonObject {
        property string defaultSize: "compact"
        property string messageStyle: "bubble"
        property string density: "comfortable"
        property real fontScale: 1
        property bool showAvatars: false
        property bool showTimestamps: false
        property bool animations: true
        property bool glass: true
        property real opacity: 1
    }
    property JsonObject behavior: JsonObject {
        property string defaultSpace: "last"
        property bool enterToSend: true
        property bool suggestions: true
        property list<string> suggestionKinds: ["clipboard", "selection", "media", "timer", "window", "desktop", "time"]
        property bool restoreLastSession: true
        property bool autoScroll: true
        property bool thinkingExpanded: false
        property bool collapseTools: true
    }
    property JsonObject strip: JsonObject {
        property bool engine: true
        property bool effort: true
        property bool context: true
        property bool cost: true
        property bool limit: true
    }
    property JsonObject effort: JsonObject {
        property string defaultLevel: "auto"
    }
    property JsonObject context: JsonObject {
        property int warnAt: 80
        property int criticalAt: 95
        property bool autoCompact: true
        property int autoCompactAt: 95
        property int keepTurns: 4
        property string compactModel: ""
        property list<var> overrides: []
    }
    property JsonObject ollama: JsonObject {
        property int numCtx: 32768
        property string endpoint: ""
        property string keepAlive: ""
    }
    property JsonObject lmstudio: JsonObject {
        property string endpoint: ""
    }
    property JsonObject providers: JsonObject {
        property int timeout: 600
        property int retries: 1
        property list<string> hidden: []
        property int probeInterval: 60
        property list<var> customHeaders: []
        property bool openrouterAttribution: true
    }
    property JsonObject picker: JsonObject {
        property bool showCapabilities: true
        property bool groupByProvider: true
        property bool showUnconnected: true
        property bool showRecent: true
    }
}
