// Generated by tools/config/gen_adapters.cjs from config/defaults/apps.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property JsonObject theming: JsonObject {
        property bool gtk: true
        property bool qt: true
        property bool kitty: true
        property bool discord: true
        property bool spicetify: true
        property bool telegram: true
        property bool firefox: true
        property bool papirus: true
        property bool nvim: true
        property bool sddm: true
    }
    property JsonObject kitty: JsonObject {
        property string font: ""
        property int fontSize: 11
    }
}
