// Generated by tools/config/gen_adapters.cjs from config/defaults/bar.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string position: "top"
    property string launcherIcon: ""
    property bool launcherIconTint: true
    property int launcherIconSize: 24
    property list<string> screenList: []
    property bool enableFirefoxPlayer: false
    property bool frameEnabled: false
    property int frameThickness: 6
    property bool pinnedOnStartup: true
    property bool hoverToReveal: true
    property int hoverRegionHeight: 8
    property bool showPinButton: true
    property bool availableOnFullscreen: false
    property bool use12hFormat: false
    property bool containBar: false
    property bool keepBarShadow: false
    property bool keepBarBorder: false
    property bool clockShowDate: false
    property bool compact: false
    property var layout: ({
            "style": "classic",
            "left": ["launcher", "workspaces", "layoutSelector", "pin"],
            "right": ["presets", "tools", "systray", "keyboardLayout", "controls", "battery", "clock", "power"],
            "drawer": []
        })
    property var panels: []
    property var moduleOptions: ({
            "windowTitle": {
                "show": "both",
                "showIcon": true,
                "maxWidth": 420
            },
            "taskbar": {
                "showPinned": true,
                "showLabels": false,
                "indicator": "dot"
            },
            "systemStats": {
                "items": ["cpu", "ram", "gpuTemp", "net"]
            },
            "weather": {
                "showDescription": true
            },
            "clock": {
                "showWeather": true,
                "face": "digital",
                "pomodoroStyle": "ring",
                "panelStyle": "column",
                "panel": {
                    "cells": []
                }
            },
            "worldClocks": {
                "zones": [
                    {
                        "label": "Tokyo",
                        "zone": "Asia/Tokyo"
                    },
                    {
                        "label": "London",
                        "zone": "Europe/London"
                    },
                    {
                        "label": "New York",
                        "zone": "America/New_York"
                    }
                ]
            },
            "workspaceTags": {
                "brackets": true
            },
            "downloads": {
                "folder": "",
                "count": 8
            },
            "workspacePreviews": {
                "count": 4
            }
        })
}
