// Generated by tools/config/gen_adapters.cjs from config/defaults/bar.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string position: "top"
    property string launcherIcon: ""
    property bool launcherIconTint: true
    property bool launcherIconFullTint: true
    property int launcherIconSize: 24
    property string pillStyle: "default"
    property list<string> screenList: []
    property bool enableFirefoxPlayer: false
    property list<var> barColor: [["surface", 0]]
    property bool frameEnabled: false
    property int frameThickness: 6
    property bool pinnedOnStartup: true
    property bool hoverToReveal: true
    property int hoverRegionHeight: 8
    property bool showPinButton: true
    property bool availableOnFullscreen: false
    property bool use12hFormat: false
    property bool containBar: false
    property bool keepBarShadow: false
    property bool keepBarBorder: false
    property bool clockShowDate: false
    property bool compact: false
    property var activities: ({
            "enabled": true,
            "presentation": "notch",
            "maxVisible": 4,
            "sources": {
                "recording": true,
                "privacy": true,
                "timers": true,
                "notificationProgress": true,
                "jobView": true,
                "browserDownloads": true,
                "steam": true,
                "terminal": true,
                "fileOps": true,
                "packages": true,
                "torrents": true,
                "aria2": true,
                "syncthing": true,
                "launchers": true
            },
            "downloads": {
                "aggregate": true,
                "showSpeed": true,
                "endpoints": {
                    "qbittorrent": "http://127.0.0.1:8080",
                    "transmission": "http://127.0.0.1:9091/transmission/rpc",
                    "deluge": "http://127.0.0.1:8112/json",
                    "aria2": "http://127.0.0.1:6800/jsonrpc",
                    "syncthing": ""
                },
                "secrets": {
                    "qbittorrent": "",
                    "transmission": "",
                    "deluge": "deluge",
                    "aria2": ""
                }
            }
        })
    property var layout: ({
            "style": "classic",
            "left": ["launcher", "workspaces", "layoutSelector", "pin"],
            "right": ["presets", "tools", "systray", "controls", "battery", "clock", "power"],
            "drawer": []
        })
    property var panels: []
    property var moduleOptions: ({
            "windowTitle": {
                "show": "both",
                "showIcon": true,
                "maxWidth": 420
            },
            "taskbar": {
                "showPinned": true,
                "showLabels": false,
                "indicator": "dot"
            },
            "systemStats": {
                "items": ["cpu", "ram", "gpuTemp", "net"]
            },
            "weather": {
                "showDescription": true
            },
            "clock": {
                "showWeather": true
            },
            "worldClocks": {
                "zones": [
                    {
                        "label": "Tokyo",
                        "zone": "Asia/Tokyo"
                    },
                    {
                        "label": "London",
                        "zone": "Europe/London"
                    },
                    {
                        "label": "New York",
                        "zone": "America/New_York"
                    }
                ]
            },
            "workspaceTags": {
                "brackets": true
            },
            "downloads": {
                "folder": "",
                "count": 8
            },
            "workspacePreviews": {
                "count": 4
            }
        })
}
