// Generated by tools/config/gen_adapters.cjs from config/defaults/compositor.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property var activeBorderColor: ["primary"]
    property int borderAngle: 45
    property var inactiveBorderColor: ["surface"]
    property int inactiveBorderAngle: 45
    property int borderSize: 2
    property int rounding: 16
    property bool syncRoundness: true
    property bool syncBorderWidth: false
    property bool syncBorderColor: false
    property bool syncShadowOpacity: false
    property bool syncShadowColor: false
    property int gapsIn: 2
    property int gapsOut: 4
    property bool smartGaps: false
    property bool dimInactive: false
    property real dimStrength: 0.1
    property string layout: "dwindle"
    property bool shadowEnabled: true
    property int shadowRange: 8
    property int shadowRenderPower: 3
    property bool shadowSharp: false
    property bool shadowIgnoreWindow: true
    property string shadowColor: "shadow"
    property string shadowColorInactive: "shadow"
    property real shadowOpacity: 0.5
    property string shadowOffset: "0 0"
    property real shadowScale: 1
    property bool blurEnabled: true
    property int blurSize: 4
    property int blurPasses: 2
    property bool blurIgnoreOpacity: true
    property bool blurExplicitIgnoreAlpha: false
    property real blurIgnoreAlphaValue: 0.2
    property bool blurNewOptimizations: true
    property bool blurXray: false
    property real blurNoise: 0
    property real blurContrast: 1
    property real blurBrightness: 1
    property real blurVibrancy: 0
    property real blurVibrancyDarkness: 0
    property bool blurSpecial: true
    property bool blurPopups: false
    property real blurPopupsIgnorealpha: 0.2
    property bool blurInputMethods: false
    property real blurInputMethodsIgnorealpha: 0.2
    property string motionProfile: "smooth"
    property real motionDurationScale: 1
    property string motionWorkspaceStyle: "auto"
    property string motionBorderLoop: "auto"
    property int motionBorderLoopSpeed: 0
    property bool motionShell: true
    property var motionOverrides: ({})
    property JsonObject borderPulse: JsonObject {
        property bool enabled: false
        property string source: "cava"
        property real intensity: 0.6
    }
}
