// Generated by tools/config/gen_adapters.cjs from config/defaults/desktop.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: false
    property int iconSize: 40
    property int spacingVertical: 16
    property string textColor: "overBackground"
    property bool blurWallpaperOnOverview: true
    property string wallpaperTransition: "grow"
    property int wallpaperTransitionDuration: 800
    property list<string> wallpaperFolders: []
    property bool depthClock: false
    property string depthClockStyle: "yozakura"
    property string depthClockPosition: "auto"
    property bool depthClockVideo: true
    property string depthClockInk: "auto"
    property bool widgetsEnabled: true
    property list<var> widgets: []
    property int widgetGrid: 24
    property string widgetVariant: "pane"
}
