// Generated by tools/config/gen_adapters.cjs from config/defaults/displays.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property list<var> monitors: []
}
