// Generated by tools/config/gen_adapters.cjs from config/defaults/dock.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: true
    property string theme: "default"
    property string position: "bottom"
    property int height: 48
    property int iconSize: 24
    property int spacing: 4
    property int margin: 4
    property int hoverRegionHeight: 16
    property bool pinnedOnStartup: false
    property bool hoverToReveal: true
    property bool availableOnFullscreen: false
    property bool showRunningIndicators: true
    property bool showPinButton: true
    property bool showOverviewButton: true
    property list<string> ignoredAppRegexes: ["quickshell.*", "xdg-desktop-portal.*"]
    property list<string> screenList: []
    property bool keepHidden: false
    property bool magnification: false
    property real magnificationScale: 1.6
    property bool launchBounce: false
}
