// Generated by tools/config/gen_adapters.cjs from config/defaults/general.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string terminal: "kitty"
    property bool terminalAdvanced: false
    property string terminalCommand: "$TERMINAL -e $COMMAND"
    property bool onboardingDone: false
}
