// Generated by tools/config/gen_adapters.cjs from config/CoreBinds.js and config/CustomBindDefaults.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io
import "../CustomBindDefaults.js" as CustomBindDefaults
import "../../modules/globals/BrandActions.js" as BrandActions

JsonAdapter {
    property JsonObject yozakura: JsonObject {
        property JsonObject launcher: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "Super_L"
            property var action: ({
                    "id": BrandActions.action("launcher"),
                    "args": {}
                })
        }
        property JsonObject dashboard: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "D"
            property var action: ({
                    "id": BrandActions.action("dashboard"),
                    "args": {}
                })
        }
        property JsonObject assistant: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "A"
            property var action: ({
                    "id": BrandActions.action("assistant"),
                    "args": {}
                })
        }
        property JsonObject clipboard: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "V"
            property var action: ({
                    "id": BrandActions.action("clipboard"),
                    "args": {}
                })
        }
        property JsonObject emoji: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "PERIOD"
            property var action: ({
                    "id": BrandActions.action("emoji"),
                    "args": {}
                })
        }
        property JsonObject notes: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "N"
            property var action: ({
                    "id": BrandActions.action("notes"),
                    "args": {}
                })
        }
        property JsonObject tmux: JsonObject {
            property list<string> modifiers: ["SUPER", "ALT"]
            property string key: "T"
            property var action: ({
                    "id": BrandActions.action("tmux"),
                    "args": {}
                })
        }
        property JsonObject wallpapers: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "COMMA"
            property var action: ({
                    "id": BrandActions.action("wallpapers"),
                    "args": {}
                })
        }
        property JsonObject voiceAi: JsonObject {
            property list<string> modifiers: ["SUPER"]
            property string key: "M"
            property var action: ({
                    "id": BrandActions.action("voice-ai"),
                    "args": {}
                })
        }
        property JsonObject dictation: JsonObject {
            property list<string> modifiers: ["SUPER", "SHIFT"]
            property string key: "M"
            property var action: ({
                    "id": BrandActions.action("dictation"),
                    "args": {}
                })
        }
        property JsonObject system: JsonObject {
            property JsonObject overview: JsonObject {
                property list<string> modifiers: ["SUPER"]
                property string key: "TAB"
                property var action: ({
                        "id": BrandActions.action("overview"),
                        "args": {}
                    })
            }
            property JsonObject powermenu: JsonObject {
                property list<string> modifiers: ["SUPER"]
                property string key: "ESCAPE"
                property var action: ({
                        "id": BrandActions.action("powermenu"),
                        "args": {}
                    })
            }
            property JsonObject config: JsonObject {
                property list<string> modifiers: ["SUPER", "SHIFT"]
                property string key: "C"
                property var action: ({
                        "id": BrandActions.action("config"),
                        "args": {}
                    })
            }
            property JsonObject lockscreen: JsonObject {
                property list<string> modifiers: ["SUPER"]
                property string key: "L"
                property var action: ({
                        "id": "system.lock",
                        "args": {}
                    })
            }
            property JsonObject tools: JsonObject {
                property list<string> modifiers: ["SUPER"]
                property string key: "S"
                property var action: ({
                        "id": BrandActions.action("tools"),
                        "args": {}
                    })
            }
            property JsonObject screenshot: JsonObject {
                property list<string> modifiers: ["SUPER", "SHIFT"]
                property string key: "S"
                property var action: ({
                        "id": BrandActions.action("screenshot"),
                        "args": {}
                    })
            }
            property JsonObject screenrecord: JsonObject {
                property list<string> modifiers: ["SUPER", "SHIFT"]
                property string key: "R"
                property var action: ({
                        "id": BrandActions.action("screenrecord"),
                        "args": {}
                    })
            }
            property JsonObject lens: JsonObject {
                property list<string> modifiers: ["SUPER", "SHIFT"]
                property string key: "A"
                property var action: ({
                        "id": BrandActions.action("lens"),
                        "args": {}
                    })
            }
            property JsonObject reload: JsonObject {
                property list<string> modifiers: ["SUPER", "ALT"]
                property string key: "B"
                property var action: ({
                        "id": BrandActions.action("reload"),
                        "args": {}
                    })
            }
            property JsonObject quit: JsonObject {
                property list<string> modifiers: ["SUPER", "CTRL", "ALT"]
                property string key: "B"
                property var action: ({
                        "id": BrandActions.action("quit"),
                        "args": {}
                    })
            }
            property JsonObject bar: JsonObject {
                property list<string> modifiers: ["SUPER", "SHIFT"]
                property string key: "B"
                property var action: ({
                        "id": BrandActions.action("bar"),
                        "args": {}
                    })
            }
            property JsonObject keybinds: JsonObject {
                property list<string> modifiers: ["SUPER"]
                property string key: "SLASH"
                property var action: ({
                        "id": BrandActions.action("keybinds"),
                        "args": {}
                    })
            }
        }
    }
    // Core binds switched off in the editor ("launcher", "system.tools").
    property list<string> disabled: []
    property list<var> custom: CustomBindDefaults.binds()
}
