// Generated by tools/config/gen_adapters.cjs from config/defaults/keyboard.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property list<var> layouts: [
        {
            "layout": "us",
            "variant": ""
        }
    ]
    property string switchBind: "alt_shift"
    property list<string> options: []
    property int repeatRate: 25
    property int repeatDelay: 600
    property bool showIndicator: true
}
