// Generated by tools/config/gen_adapters.cjs from config/defaults/layout.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property JsonObject launcher: JsonObject {
        property string host: "notch"
        property string resultStyle: "list"
        property bool preview: false
        property bool icons: true
        property bool compactWhenEmpty: false
    }
    property JsonObject dashboard: JsonObject {
        property string host: "notch"
        property string home: "composed"
        property list<var> tabs: [
            {
                "id": "widgets",
                "visible": true
            },
            {
                "id": "wallpapers",
                "visible": true
            },
            {
                "id": "metrics",
                "visible": true
            }
        ]
        property JsonObject grid: JsonObject {
            property int cols: 4
            property list<var> cells: []
        }
    }
    property JsonObject sheet: JsonObject {
        property string side: "auto"
    }
    property bool backdrop: false
    property JsonObject powermenu: JsonObject {
        property string style: "notch"
    }
    property JsonObject tools: JsonObject {
        property string style: "notch"
    }
    property JsonObject cheatsheet: JsonObject {
        property string host: "fullscreen"
    }
    property JsonObject osd: JsonObject {
        property string position: "auto"
        property string style: "pill"
        property int timeout: 2500
    }
}
