// Generated by tools/config/gen_adapters.cjs from config/defaults/lockscreen.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string position: "bottom"
    property string style: "glass"
    property string tone: "style"
    property real blur: -1
    property bool showMedia: true
    property bool showVisualizer: true
    property bool showStatus: true
}
