// Generated by tools/config/gen_adapters.cjs from config/defaults/notch.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string theme: "default"
    property string position: "top"
    property int hoverRegionHeight: 8
    property bool keepHidden: false
    property string noMediaDisplay: "userHost"
    property string customText: "Yozakura"
    property bool disableHoverExpansion: true
    property int hoverExpandDelay: 90
    property int hoverCollapseDelay: 200
    property string expandOn: "hover"
    property int expandedMediaWidth: 440
    property int mediaAnimationDuration: 160
    property int expandedArtworkSize: 64
    property int microphoneNoticeDuration: 1800
    property bool visualizer: true
    property string style: "attached"
    property list<var> activities: []
    property bool osd: false
}
