// Generated by tools/config/gen_adapters.cjs from config/defaults/notch.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: true
    property string position: "top"
    property string align: "center"
    property int hoverRegionHeight: 8
    property bool keepHidden: false
    property string noMediaDisplay: "userHost"
    property string customText: "Yozakura"
    property bool disableHoverExpansion: true
    property int hoverExpandDelay: 90
    property int hoverCollapseDelay: 200
    property string expandOn: "hover"
    property int expandedMediaWidth: 440
    property int mediaAnimationDuration: 160
    property int expandedArtworkSize: 64
    property int microphoneNoticeDuration: 1800
    property bool visualizer: true
    property string style: "attached"
    property list<var> activities: []
    property var liveActivities: ({
            "enabled": true,
            "presentation": "notch",
            "maxVisible": 4,
            "sources": {
                "recording": true,
                "privacy": true,
                "timers": true,
                "tasks": true,
                "notificationProgress": true,
                "jobView": true,
                "browserDownloads": true,
                "steam": true,
                "terminal": true,
                "fileOps": true,
                "packages": true,
                "torrents": true,
                "aria2": true,
                "syncthing": true,
                "launchers": true
            },
            "downloads": {
                "aggregate": true,
                "showSpeed": true,
                "endpoints": {
                    "qbittorrent": "http://127.0.0.1:8080",
                    "transmission": "http://127.0.0.1:9091/transmission/rpc",
                    "deluge": "http://127.0.0.1:8112/json",
                    "aria2": "http://127.0.0.1:6800/jsonrpc",
                    "syncthing": ""
                },
                "secrets": {
                    "qbittorrent": "",
                    "transmission": "",
                    "deluge": "deluge",
                    "aria2": ""
                }
            }
        })
}
