// Generated by tools/config/gen_adapters.cjs from config/defaults/notifications.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string presentation: "auto"
    property string position: "auto"
    property list<string> screens: []
    property int timeout: 5000
    property int maxVisible: 3
    property bool groupByApp: true
    property int historySize: 100
    property JsonObject sound: JsonObject {
        property bool enabled: false
        property string file: ""
    }
    property list<var> rules: []
    property JsonObject dnd: JsonObject {
        property bool enabled: false
        property bool allowCritical: true
        property JsonObject schedule: JsonObject {
            property bool enabled: false
            property string from: "22:00"
            property string to: "07:00"
            property list<var> days: [0, 1, 2, 3, 4, 5, 6]
        }
    }
}
