// Generated by tools/config/gen_adapters.cjs from config/defaults/overview.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string style: "grid"
    property int rows: 2
    property int columns: 5
    property real scale: 0.15
    property real workspaceSpacing: 8
}
