// Generated by tools/config/gen_adapters.cjs from config/defaults/performance.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool blurTransition: true
    property bool windowPreview: true
    property bool wavyLine: true
    property bool rotateCoverArt: true
    property bool pauseWallpaperOnFullscreen: true
    property bool pauseWallpaperWhenCovered: true
    property bool dashboardPersistTabs: false
    property int dashboardMaxPersistentTabs: 2
}
