// Generated by tools/config/gen_adapters.cjs from config/defaults/prefix.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property string clipboard: "cc"
    property string emoji: "ee"
    property string tmux: "tt"
    property string wallpapers: "ww"
    property string notes: "nn"
    property string calculator: "="
    property string commands: ">"
    property string files: "ff"
    property string ai: "?"
    property string timers: "t"
    property JsonObject launcher: JsonObject {
        property list<string> order: ["calculator", "commands", "timers", "apps", "specials", "routines", "wallpapers", "files", "ai"]
        property list<string> disabled: []
        property bool aiOnTab: true
        property bool filesInMixed: true
        property string fileBackend: "auto"
        property int fileMaxResults: 30
        property list<string> fileExcludes: [".git", "node_modules", ".cache", ".local/share/Trash", "target", "__pycache__", ".venv"]
        property int currencyRefreshHours: 12
    }
}
