// Generated by tools/config/gen_adapters.cjs from config/defaults/specials.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: true
    property int launchTimeout: 20000
    property int preloadDelay: 4000
    property list<var> workspaces: []
}
