// Generated by tools/config/gen_adapters.cjs from config/defaults/system.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property list<string> disks: ["/"]
    property string language: "auto"
    property bool updateServiceEnabled: true
    property JsonObject idle: JsonObject {
        property JsonObject general: JsonObject {
            property string lock_cmd: "yozakura lock"
            property string before_sleep_cmd: "loginctl lock-session"
            property string after_sleep_cmd: "yozakura screen on"
        }
        property list<var> listeners: [
            {
                "timeout": 150,
                "onTimeout": "yozakura brightness 10 -s",
                "onResume": "yozakura brightness -r"
            },
            {
                "timeout": 300,
                "onTimeout": "loginctl lock-session"
            },
            {
                "timeout": 330,
                "onTimeout": "yozakura screen off",
                "onResume": "yozakura screen on"
            },
            {
                "timeout": 1800,
                "onTimeout": "yozakura suspend"
            }
        ]
    }
    property JsonObject ocr: JsonObject {
        property bool eng: true
        property bool spa: true
        property bool lat: false
        property bool jpn: false
        property bool chi_sim: false
        property bool chi_tra: false
        property bool kor: false
        property bool rus: false
    }
    property JsonObject pomodoro: JsonObject {
        property int workTime: 1500
        property int restTime: 300
        property bool autoStart: false
        property bool syncSpotify: false
    }
    property JsonObject timers: JsonObject {
        property string notchStyle: "ring"
        property bool showSeconds: true
        property bool pulseOnFinish: true
        property bool alarmPanel: true
        property bool sound: true
        property string soundFile: ""
        property int alarmRepeat: 3
        property int alarmInterval: 4
        property bool phaseSound: true
        property bool showStopwatch: true
        property int reminderLead: 15
        property string clockClick: "popup"
        property string noteTitle: ""
    }
    property JsonObject focus: JsonObject {
        property int minutes: 50
        property bool dnd: true
        property bool hideBadges: true
        property bool summary: true
    }
    property JsonObject clipboard: JsonObject {
        property bool tmpfs: false
    }
}
