// Generated by tools/config/gen_adapters.cjs from config/defaults/terminal.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: false
    property string engine: "starship"
    property string prompt: "sakura-powerline"
    property string greeting: "none"
    property int padding: 12
    property string cursorShape: "beam"
    property bool cursorBlink: true
}
