// Generated by tools/config/gen_adapters.cjs from config/defaults/voice.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property bool enabled: true
    property string model: "large-v3-turbo-q5_0"
    property string language: "auto"
    property string activation: "push-to-talk"
    property bool useGpu: true
    property int maxSeconds: 60
    property int idleTimeout: 300
    property bool vadAutoStop: true
    property int vadSilenceMs: 1200
    property real vadSensitivity: 0.5
    property int noSpeechTimeout: 8
    property bool serverVad: true
    property string typingMethod: "auto"
    property bool punctuation: true
    property bool trailingSpace: true
    property bool aiAutoSend: false
    property int previewMs: 500
}
