// Generated by tools/config/gen_adapters.cjs from config/defaults/workspaces.js and config/meta/AdapterTypes.js.
// Do not edit: change the source and run `make schema`.
import Quickshell.Io

JsonAdapter {
    property int shown: 10
    property bool showAppIcons: true
    property bool alwaysShowNumbers: false
    property bool showNumbers: false
    property bool dynamic: false
    property bool showSpecialWorkspace: true
    property int specialWorkspaceAnimationDuration: 100
    property string specialWorkspaceFont: ""
    property string numeralStyle: "arabic"
    property string numeralFont: ""
    property string indicatorStyle: "pill"
}
