.pragma library

var data = {
    "oledMode": false,
    "lightMode": false,
    "roundness": 16,
    "font": "Roboto Condensed",
    "fontSize": 14,
    "monoFont": "Iosevka Nerd Font Mono",
    "monoFontSize": 14,
    "tintIcons": false,
    // Icon font weight: regular | bold | fill (modules/theme/IconWeights.js).
    "icons": {
        "weight": "bold"
    },
    // Type roles: body follows `font`; heading "" = the body font;
    // headingCase: none | upper | lower | title.
    "type": {
        "heading": "",
        "headingCase": "none"
    },
    "enableCorners": true,
    "animDuration": 300,
    // Metrics density: compact | cozy | roomy (cozy = the historical sizes).
    "density": "cozy",
    // Visual language (modules/theme/VisualLanguage.js): ink | glass | tiles | classic.
    "language": "ink",
    // Corner shape: round | squircle | cut | tab; popupCorners "" follows corners.
    "shape": {
        "corners": "round",
        "popupCorners": "cut",
        "cutSize": 10
    },
    // Bar popups and menus: entry motion (fade-scale | slide-from-anchor |
    // morph-from-bar | unfold), a tail toward the anchor, gap to the anchor.
    "popup": {
        "entry": "fade-scale",
        "tail": false,
        "gap": 8
    },
    // Decorative signatures (on since the theme overhaul default shift).
    "signatures": {
        "brushHighlight": true,
        "petals": true,
        "petalShape": "petal"
    },
    "paletteTransitionDuration": 600,
    "shadowOpacity": 0.5,
    "shadowColor": "shadow",
    "shadowXOffset": 0,
    "shadowYOffset": 0,
    "shadowBlur": 1,
    "terminalOpacity": -1,
    // Signature texture on the shell's surfaces (registry:
    // modules/components/surfaceeffects/SurfaceEffects.js): none | crt | ink.
    "surfaceEffect": "none",
    "surfaceEffectOptions": {
        "intensity": 0.5,
        "flicker": true,
        "grain": 0.6,
        "brushHighlights": true
    },
    // Glass system (modules/theme/GlassModel.js). -1 = auto/inherit:
    // amount -1 = the preset's own amount (its look is unchanged),
    // referenceAmount -1 = derived from the preset's sr*/terminal opacities.
    "glass": {
        "enabled": true,
        "amount": -1,
        "referenceAmount": -1,
        "tintRole": "primary",
        "highlightRole": "overBackground",
        // Shell-only overrides; blur and shadow values belong to the
        // compositor (compositor.blur*, shadowRange: KeyAliases.js).
        "advanced": {
            "opacity": -1,
            "tintStrength": -1,
            "borderHighlight": -1
        },
        "surfaces": {
            "windows": { "amount": -1, "activeOpacity": -1, "inactiveOpacity": -1 },
            "terminal": { "amount": -1 },
            "popups": { "amount": -1 },
            "bar": { "amount": -1 },
            "notch": { "amount": -1 },
            "dock": { "amount": -1 },
            "sidebars": { "amount": -1 },
            "lockscreen": { "amount": -1 },
            "settings": { "amount": -1 },
            "widgets": { "amount": -1 }
        }
    },
    "srBg": {
        "label": "Background",
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srPopup": {
        "label": "Popup",
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 2],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srInternalBg": {
        "label": "Internal BG",
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srBarBg": {
        "label": "Bar BG",
        "gradient": [["surfaceDim", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "surfaceDim",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 0.0
    },
    "srFrame": {
        "label": "Frame",
        "inheritBg": true,
        "gradient": [["background", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surface",
        "halftoneBackgroundColor": "background",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srPane": {
        "label": "Pane",
        "gradient": [["surface", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surfaceBright",
        "halftoneBackgroundColor": "surface",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srCommon": {
        "label": "Common",
        "gradient": [["surface", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "background",
        "halftoneBackgroundColor": "surface",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srFocus": {
        "label": "Focus",
        "gradient": [["surfaceBright", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "surfaceVariant",
        "halftoneBackgroundColor": "surfaceBright",
        "border": ["surfaceBright", 0],
        "itemColor": "overBackground",
        "opacity": 1.0
    },
    "srPrimary": {
        "label": "Primary",
        "gradient": [["primary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overPrimaryContainer",
        "halftoneBackgroundColor": "primary",
        "border": ["primary", 0],
        "itemColor": "overPrimary",
        "opacity": 1.0
    },
    "srPrimaryFocus": {
        "label": "Primary Focus",
        "gradient": [["overPrimaryContainer", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "primary",
        "halftoneBackgroundColor": "overPrimaryContainer",
        "border": ["overBackground", 0],
        "itemColor": "overPrimary",
        "opacity": 1.0
    },
    "srOverPrimary": {
        "label": "Over Primary",
        "gradient": [["overPrimary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "primaryContainer",
        "halftoneBackgroundColor": "overPrimary",
        "border": ["overPrimary", 0],
        "itemColor": "primary",
        "opacity": 1.0
    },
    "srSecondary": {
        "label": "Secondary",
        "gradient": [["secondary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overSecondaryContainer",
        "halftoneBackgroundColor": "secondary",
        "border": ["secondary", 0],
        "itemColor": "overSecondary",
        "opacity": 1.0
    },
    "srSecondaryFocus": {
        "label": "Secondary Focus",
        "gradient": [["overSecondaryContainer", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "secondary",
        "halftoneBackgroundColor": "overSecondaryContainer",
        "border": ["overBackground", 0],
        "itemColor": "overSecondary",
        "opacity": 1.0
    },
    "srOverSecondary": {
        "label": "Over Secondary",
        "gradient": [["overSecondary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "secondaryContainer",
        "halftoneBackgroundColor": "overSecondary",
        "border": ["overSecondary", 0],
        "itemColor": "secondary",
        "opacity": 1.0
    },
    "srTertiary": {
        "label": "Tertiary",
        "gradient": [["tertiary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overTertiaryContainer",
        "halftoneBackgroundColor": "tertiary",
        "border": ["tertiary", 0],
        "itemColor": "overTertiary",
        "opacity": 1.0
    },
    "srTertiaryFocus": {
        "label": "Tertiary Focus",
        "gradient": [["overTertiaryContainer", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "tertiary",
        "halftoneBackgroundColor": "overTertiaryContainer",
        "border": ["overBackground", 0],
        "itemColor": "overTertiary",
        "opacity": 1.0
    },
    "srOverTertiary": {
        "label": "Over Tertiary",
        "gradient": [["overTertiary", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "tertiaryContainer",
        "halftoneBackgroundColor": "overTertiary",
        "border": ["overTertiary", 0],
        "itemColor": "tertiary",
        "opacity": 1.0
    },
    "srError": {
        "label": "Error",
        "gradient": [["error", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "overErrorContainer",
        "halftoneBackgroundColor": "error",
        "border": ["error", 0],
        "itemColor": "overError",
        "opacity": 1.0
    },
    "srErrorFocus": {
        "label": "Error Focus",
        "gradient": [["overBackground", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "error",
        "halftoneBackgroundColor": "overErrorContainer",
        "border": ["overBackground", 0],
        "itemColor": "overError",
        "opacity": 1.0
    },
    "srOverError": {
        "label": "Over Error",
        "gradient": [["overError", 0.0]],
        "gradientType": "linear",
        "gradientAngle": 0,
        "gradientCenterX": 0.5,
        "gradientCenterY": 0.5,
        "halftoneDotMin": 0.0,
        "halftoneDotMax": 2.0,
        "halftoneStart": 0.0,
        "halftoneEnd": 1.0,
        "halftoneDotColor": "errorContainer",
        "halftoneBackgroundColor": "overError",
        "border": ["overError", 0],
        "itemColor": "error",
        "opacity": 1.0
    }
}
