package compositor

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"yozakura/backend/pkg/brand"
)

// Hyprland appearance overlay.
//
// yozd renders ~/.local/share/yozakura/hyprland.{lua,conf} from yozd.toml,
// but its TOML schema only carries a subset of the appearance Yozakura
// applies live through hl.config(): no inactive-border gradient, no
// shadow color_inactive/render_power/offset/scale, and only
// enabled/size/passes for blur. Every yozd regen + Hyprland reload used
// to drop the rest and fall back to Hyprland defaults.
//
// When the shell sends the full hl.config() table (Input.Hyprland), the
// backend points yozd at hyprland.yozd.{lua,conf} instead and owns
// hyprland.{lua,conf} itself: each loads yozd's output and then applies
// the exact table the shell dispatches live. The user's config keeps
// loading the same path, so existing installs pick this up without edits.

const (
	// HyprlandEntryLua / HyprlandEntryConf are the files users load from
	// their Hyprland config (see `yozakura install hyprland`).
	HyprlandEntryLua  = "hyprland.lua"
	HyprlandEntryConf = "hyprland.conf"
	// DaemonHyprlandTarget is where yozd renders when the overlay is
	// active; yozd derives the .conf sibling from it.
	DaemonHyprlandTarget = "hyprland." + brand.Daemon + ".lua"
	daemonHyprlandConf   = "hyprland." + brand.Daemon + ".conf"
)

// hyprlandTarget returns the [target] hyprland path for the given input.
// Without an overlay (older shells) yozd keeps writing the entry files.
func hyprlandTarget(in Input) string {
	if in.Hyprland != nil {
		return DaemonHyprlandTarget
	}
	return HyprlandEntryLua
}

// HyprlandOverlayFiles returns the entry files (absolute path -> content)
// to write next to the TOML, or nil when the input carries no overlay.
func HyprlandOverlayFiles(in Input, dir string, gameMode bool) map[string]string {
	if in.Hyprland == nil {
		return nil
	}
	cfg := in.Hyprland
	if gameMode {
		cfg = gameModeHyprland(cfg)
	}
	return map[string]string{
		filepath.Join(dir, HyprlandEntryLua):  RenderHyprlandLua(cfg, filepath.Join(dir, DaemonHyprlandTarget)) + renderExtrasLua(in, gameMode),
		filepath.Join(dir, HyprlandEntryConf): RenderHyprlandConf(cfg, filepath.Join(dir, daemonHyprlandConf)) + renderExtrasConf(in, gameMode),
	}
}

const overlayNote = "Generated by " + brand.DisplayName + " - do not edit, it is rewritten on every compositor change.\n" +
	brand.Daemon + " renders binds, rules and animations into the file loaded below; the\n" +
	"appearance after it is the exact table " + brand.DisplayName + " applies live, which " + brand.Daemon + "'s\n" +
	"TOML schema cannot carry (gradients, shadow colors, blur extras).\n"

// RenderHyprlandLua renders the Lua entry file: load yozd's output (if it
// exists yet), then apply the appearance table. pcall keeps a rejected key
// from aborting the rest of the user's config.
func RenderHyprlandLua(cfg map[string]any, basePath string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimSuffix(overlayNote, "\n"), "\n") {
		b.WriteString("-- " + line + "\n")
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "local base = loadfile(%s)\n", luaQuote(basePath))
	b.WriteString("if base then base() end\n\n")
	b.WriteString("local ok, err = pcall(hl.config, ")
	b.WriteString(luaValue(cfg, 0))
	b.WriteString(")\n")
	b.WriteString("if not ok then print(\"" + brand.AppID + ": appearance overlay rejected: \" .. tostring(err)) end\n")
	return b.String()
}

// RenderHyprlandConf renders the hyprlang entry file: source yozd's
// output, then the same appearance as nested categories.
func RenderHyprlandConf(cfg map[string]any, basePath string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimSuffix(overlayNote, "\n"), "\n") {
		b.WriteString("# " + line + "\n")
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "source = %s\n", basePath)
	for _, k := range sortedKeys(cfg) {
		if sub, ok := cfg[k].(map[string]any); ok {
			b.WriteString("\n")
			writeHyprlangCategory(&b, k, sub, 0)
		}
	}
	return b.String()
}

// Option groups whose nested Lua tables map to dotted hyprlang keys
// (general.col.active_border) rather than to categories.
var hyprlangDottedGroups = map[string]bool{"col": true}

func writeHyprlangCategory(b *strings.Builder, name string, cfg map[string]any, depth int) {
	indent := strings.Repeat("    ", depth)
	b.WriteString(indent + name + " {\n")
	inner := indent + "    "
	for _, k := range sortedKeys(cfg) {
		v := cfg[k]
		sub, isMap := v.(map[string]any)
		switch {
		case isMap && hyprlangDottedGroups[k]:
			for _, sk := range sortedKeys(sub) {
				fmt.Fprintf(b, "%s%s.%s = %s\n", inner, k, sk, hyprlangValue(sub[sk]))
			}
		case isMap && !isGradient(sub):
			writeHyprlangCategory(b, k, sub, depth+1)
		default:
			if s := hyprlangValue(v); s != "" {
				fmt.Fprintf(b, "%s%s = %s\n", inner, k, s)
			}
		}
	}
	b.WriteString(indent + "}\n")
}

func isGradient(m map[string]any) bool {
	_, ok := m["colors"].([]any)
	return ok
}

func hyprlangValue(v any) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	case bool:
		return strconv.FormatBool(t)
	case float64:
		return formatNumber(t)
	case int:
		return strconv.Itoa(t)
	case []any:
		parts := make([]string, 0, len(t))
		for _, e := range t {
			parts = append(parts, hyprlangValue(e))
		}
		return strings.Join(parts, " ")
	case map[string]any:
		if isGradient(t) {
			s := hyprlangValue(t["colors"])
			if a, ok := t["angle"]; ok {
				s += " " + hyprlangValue(a) + "deg"
			}
			return s
		}
	}
	return ""
}

var luaIdent = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// luaValue renders a JSON-decoded value as an indented Lua literal with
// sorted keys (deterministic output, so unchanged settings produce
// byte-identical files).
func luaValue(v any, depth int) string {
	switch t := v.(type) {
	case nil:
		return "nil"
	case string:
		return luaQuote(t)
	case bool:
		return strconv.FormatBool(t)
	case float64:
		return formatNumber(t)
	case int:
		return strconv.Itoa(t)
	case []any:
		parts := make([]string, 0, len(t))
		for _, e := range t {
			parts = append(parts, luaValue(e, depth+1))
		}
		return "{ " + strings.Join(parts, ", ") + " }"
	case map[string]any:
		if len(t) == 0 {
			return "{}"
		}
		inner := strings.Repeat("    ", depth+1)
		var b strings.Builder
		b.WriteString("{\n")
		for _, k := range sortedKeys(t) {
			if !luaIdent.MatchString(k) {
				continue
			}
			fmt.Fprintf(&b, "%s%s = %s,\n", inner, k, luaValue(t[k], depth+1))
		}
		b.WriteString(strings.Repeat("    ", depth) + "}")
		return b.String()
	}
	return "nil"
}

func luaQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

func formatNumber(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// gameModeHyprland mirrors CompositorConfig.applyGameModeLive on a copy of
// the overlay so the persisted entry files never re-enable what GameMode
// turned off.
func gameModeHyprland(cfg map[string]any) map[string]any {
	out := deepCopyMap(cfg)
	general := subMap(out, "general")
	general["gaps_in"] = float64(0)
	general["gaps_out"] = float64(0)
	general["border_size"] = float64(1)
	deco := subMap(out, "decoration")
	deco["rounding"] = float64(0)
	deco["active_opacity"] = 1.0
	deco["inactive_opacity"] = 1.0
	deco["fullscreen_opacity"] = 1.0
	subMap(deco, "shadow")["enabled"] = false
	subMap(deco, "blur")["enabled"] = false
	subMap(out, "animations")["enabled"] = false
	return out
}

func subMap(m map[string]any, key string) map[string]any {
	if s, ok := m[key].(map[string]any); ok {
		return s
	}
	s := map[string]any{}
	m[key] = s
	return s
}

func deepCopyMap(m map[string]any) map[string]any {
	out := make(map[string]any, len(m))
	for k, v := range m {
		out[k] = deepCopyValue(v)
	}
	return out
}

func deepCopyValue(v any) any {
	switch t := v.(type) {
	case map[string]any:
		return deepCopyMap(t)
	case []any:
		c := make([]any, len(t))
		for i, e := range t {
			c[i] = deepCopyValue(e)
		}
		return c
	}
	return v
}
